ALTER TABLE vets ADD COLUMN IF NOT EXISTS website VARCHAR DEFAULT '';
ALTER TABLE vets ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '';
ALTER TABLE vets ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';
