ALTER TABLE weight_entries ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE weight_entries ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';
ALTER TABLE weight_entries ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
