// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pet-profile/GuardianCockpit.tsx": () => import("../components/mockups/pet-profile/GuardianCockpit.tsx"),
  "./components/mockups/pet-profile/GuardianCockpitCoastalTeal.tsx": () => import("../components/mockups/pet-profile/GuardianCockpitCoastalTeal.tsx"),
  "./components/mockups/pet-profile/GuardianCockpitMidnightOrchid.tsx": () => import("../components/mockups/pet-profile/GuardianCockpitMidnightOrchid.tsx"),
  "./components/mockups/pet-profile/GuardianCockpitSunlitCitrus.tsx": () => import("../components/mockups/pet-profile/GuardianCockpitSunlitCitrus.tsx"),
  "./components/mockups/pet-profile/GuardianShelterDeepTealClay.tsx": () => import("../components/mockups/pet-profile/GuardianShelterDeepTealClay.tsx"),
  "./components/mockups/pet-profile/GuardianShelterEucalyptusSaffron.tsx": () => import("../components/mockups/pet-profile/GuardianShelterEucalyptusSaffron.tsx"),
  "./components/mockups/pet-profile/GuardianShelterHarbourOchre.tsx": () => import("../components/mockups/pet-profile/GuardianShelterHarbourOchre.tsx"),
  "./components/mockups/pet-profile/GuardianShelterLagoonMarigold.tsx": () => import("../components/mockups/pet-profile/GuardianShelterLagoonMarigold.tsx"),
  "./components/mockups/pet-profile/GuardianShelterOliveApricot.tsx": () => import("../components/mockups/pet-profile/GuardianShelterOliveApricot.tsx"),
  "./components/mockups/pet-profile/GuardianShelterOliveGoldenOchre.tsx": () => import("../components/mockups/pet-profile/GuardianShelterOliveGoldenOchre.tsx"),
  "./components/mockups/pet-profile/GuardianShelterSageGolden.tsx": () => import("../components/mockups/pet-profile/GuardianShelterSageGolden.tsx")
};
