import React, { useState } from 'react';
import {
  Activity, Bell, CalendarDays, Check, ChevronDown, ChevronRight, Droplets,
  HeartPulse, Home, Menu, MoreHorizontal, PawPrint, Pill, Plus, Settings2,
  ShieldCheck, Sparkles, Stethoscope, X,
} from 'lucide-react';

type Task = { id: number; time: string; title: string; detail: string; kind: 'medicine' | 'care' | 'walk'; done: boolean };
const initialTasks: Task[] = [
  { id: 1, time: '08:00', title: 'Breakfast + probiotic', detail: '1 scoop · with food', kind: 'medicine', done: true },
  { id: 2, time: '12:30', title: 'Midday water check', detail: 'Target 220 ml', kind: 'care', done: false },
  { id: 3, time: '17:45', title: 'Evening walk', detail: '20–30 minutes · gentle pace', kind: 'walk', done: false },
  { id: 4, time: '21:00', title: 'Joint supplement', detail: '1 chew · after dinner', kind: 'medicine', done: false },
];
const petData = [
  { name: 'Miso', species: 'Shiba Inu · 4 yr', initials: 'MI', tone: '#bd8666', status: 'Doing well' },
  { name: 'Basil', species: 'Tabby cat · 2 yr', initials: 'BA', tone: '#668d87', status: 'All caught up' },
];

function IconTile({ kind }: { kind: Task['kind'] }) {
  const Icon = kind === 'medicine' ? Pill : kind === 'walk' ? Activity : Droplets;
  return <span className={`dt-icon dt-${kind}`}><Icon size={17} strokeWidth={1.8} /></span>;
}

export default function GuardianShelterDeepTealClay() {
  const [activePet, setActivePet] = useState(0);
  const [tasks, setTasks] = useState(initialTasks);
  const [tab, setTab] = useState('Today');
  const [showPetMenu, setShowPetMenu] = useState(false);
  const [showComposer, setShowComposer] = useState(false);
  const [notice, setNotice] = useState('');
  const pet = petData[activePet];
  const completed = tasks.filter((task) => task.done).length;
  const toast = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2400); };
  const toggleTask = (id: number) => setTasks((current) => current.map((task) => task.id === id ? { ...task, done: !task.done } : task));

  return <main className="dt-shell">
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500&display=swap');
      .dt-shell{min-height:100vh;background:#edf3f0;color:#183a3a;font-family:'DM Sans',sans-serif;display:flex}
      .dt-sidebar{width:226px;flex:0 0 226px;background:#143f40;color:#f2f6f2;padding:25px 16px 20px;display:flex;flex-direction:column}
      .dt-brand{display:flex;align-items:center;gap:10px;padding:0 10px 32px;font-weight:700;letter-spacing:-.03em}.dt-brand-mark{width:30px;height:30px;border-radius:10px;background:#d3a069;display:grid;place-items:center;color:#143f40}
      .dt-nav-label{color:#86a7a2;font-size:10px;letter-spacing:.14em;text-transform:uppercase;margin:8px 12px 10px}.dt-nav{display:flex;align-items:center;gap:11px;width:100%;border:0;background:none;color:#aac1bc;padding:11px 12px;border-radius:11px;text-align:left;font:500 13px 'DM Sans';cursor:pointer}.dt-nav.active{color:#fff;background:#235d5b}.dt-nav:hover{background:#1d514f;color:#fff}.dt-sidebar-foot{margin-top:auto;border-top:1px solid #2c5a59;padding-top:18px}
      .dt-main{min-width:0;flex:1}.dt-topbar{height:78px;background:#f7faf7;border-bottom:1px solid #d8e5df;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(20px,4vw,56px)}.dt-menu{display:none;border:0;background:none;color:#143f40}.dt-crumb{font-size:12px;color:#78908c;display:flex;gap:8px;align-items:center}.dt-crumb strong{color:#285654}.dt-top-actions{display:flex;gap:12px;align-items:center}.dt-icon-button{width:38px;height:38px;border:1px solid #ccded7;background:#fff;border-radius:11px;display:grid;place-items:center;color:#52746e;cursor:pointer}.dt-avatar{width:37px;height:37px;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:11px;font-weight:700}
      .dt-content{max-width:1120px;margin:0 auto;padding:43px clamp(20px,4vw,56px) 60px}.dt-welcome{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:32px}.dt-eyebrow{color:#a66f42;text-transform:uppercase;letter-spacing:.15em;font-size:10px;font-weight:700;margin-bottom:10px}.dt-h1{font-size:clamp(28px,4vw,40px);line-height:1.05;letter-spacing:-.055em;margin:0;color:#193c3c}.dt-h1 em{font-family:Fraunces,serif;font-weight:500;color:#236866;font-style:normal}.dt-date{color:#708983;font-size:13px;text-align:right;line-height:1.5}.dt-date b{color:#315957;display:block;font-size:14px}
      .dt-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(260px,.8fr);gap:22px}.dt-card{background:#fbfdfb;border:1px solid #d8e6df;border-radius:18px;box-shadow:0 8px 24px rgba(26,70,66,.07)}.dt-hero{padding:24px;background:#d8e8e2;border-color:#c2dcd3;position:relative;overflow:hidden}.dt-hero:after{content:'';position:absolute;right:-55px;top:-75px;width:220px;height:220px;border-radius:50%;border:1px solid rgba(35,104,102,.22);box-shadow:0 0 0 22px rgba(35,104,102,.06),0 0 0 44px rgba(35,104,102,.04)}
      .dt-pet-select{position:relative;z-index:2;display:flex;align-items:center;justify-content:space-between}.dt-pet-button{display:flex;align-items:center;gap:12px;background:none;border:0;padding:0;cursor:pointer;color:#173e3d;text-align:left}.dt-pet-photo{width:54px;height:54px;border-radius:17px;display:grid;place-items:center;color:#fff;font-weight:700;letter-spacing:.06em;box-shadow:inset 0 0 0 4px rgba(255,255,255,.3)}.dt-pet-name{font-weight:700;font-size:20px;letter-spacing:-.04em;display:block}.dt-pet-meta{color:#52746e;font-size:12px;display:block;margin-top:2px}.dt-pet-menu{position:absolute;right:24px;top:84px;background:#fbfdfb;border:1px solid #cbded6;border-radius:12px;padding:5px;box-shadow:0 12px 30px #143f4020;z-index:5;min-width:150px}.dt-pet-menu button{width:100%;border:0;background:none;padding:9px;text-align:left;border-radius:8px;color:#385c58;cursor:pointer;font:500 12px 'DM Sans'}.dt-pet-menu button:hover{background:#e7f0eb}
      .dt-health{margin-top:27px;display:flex;align-items:flex-end;justify-content:space-between;position:relative;z-index:1}.dt-health-label{color:#52746e;font-size:12px;margin-bottom:7px}.dt-health-score{font-size:37px;letter-spacing:-.06em;font-weight:700;color:#193f3e}.dt-health-score small{font-size:14px;color:#75908a;font-weight:500;letter-spacing:0}.dt-ring{width:91px;height:91px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(#236866 0 82%,#b7d2c9 82% 100%);position:relative}.dt-ring:after{content:'';position:absolute;inset:8px;background:#d8e8e2;border-radius:50%}.dt-ring span{position:relative;z-index:1;font-size:18px;font-weight:700;color:#235b59}.dt-progress{height:5px;background:#b7d2c9;border-radius:9px;margin-top:17px;overflow:hidden;position:relative;z-index:1}.dt-progress i{display:block;width:82%;height:100%;background:#236866;border-radius:9px}
      .dt-card-head{display:flex;align-items:center;justify-content:space-between;padding:21px 23px 14px}.dt-card-title{font-size:15px;font-weight:700;letter-spacing:-.02em}.dt-card-link{color:#236866;border:0;background:none;font:600 11px 'DM Sans';cursor:pointer}.dt-tasks{padding:0 12px 10px}.dt-task{display:grid;grid-template-columns:50px 35px 1fr 28px;align-items:center;gap:10px;padding:13px 11px;border-top:1px solid #e6efea}.dt-task-time{font-size:11px;color:#829792;font-variant-numeric:tabular-nums}.dt-icon{width:33px;height:33px;border-radius:10px;display:grid;place-items:center}.dt-medicine{background:#f0e1d6;color:#a96d43}.dt-care{background:#dcece6;color:#29716d}.dt-walk{background:#e5ebe2;color:#687f5b}.dt-task-title{font-size:13px;font-weight:600;color:#315552;display:block}.dt-task-detail{font-size:11px;color:#8a9b96;margin-top:3px;display:block}.dt-task.is-done .dt-task-title{text-decoration:line-through;color:#a2afaa}.dt-check{width:23px;height:23px;border:1px solid #c9dcd4;border-radius:50%;background:#fff;display:grid;place-items:center;color:transparent;cursor:pointer}.dt-check.checked{background:#29716d;border-color:#29716d;color:#fff}
      .dt-stat-card{padding:22px 23px}.dt-stat-row{display:flex;justify-content:space-between;align-items:center}.dt-stat-main{font-size:30px;font-weight:700;letter-spacing:-.05em;color:#204745}.dt-stat-main small{font-size:12px;font-weight:500;color:#82958f;letter-spacing:0}.dt-stat-note{font-size:11px;color:#7c918b;margin-top:5px}.dt-stat-icon{width:37px;height:37px;border-radius:12px;background:#dcece6;color:#29716d;display:grid;place-items:center}.dt-mini-chart{display:flex;align-items:flex-end;gap:7px;height:53px;margin-top:22px}.dt-mini-chart i{flex:1;background:#b9d8cf;border-radius:5px 5px 2px 2px;min-height:15px}.dt-mini-chart i:nth-child(4),.dt-mini-chart i:last-child{background:#29716d}.dt-side-stack{display:flex;flex-direction:column;gap:22px}.dt-next{padding:22px 23px}.dt-next-box{background:#e8eee5;border-radius:12px;padding:14px;margin-top:14px;display:flex;gap:11px;align-items:center}.dt-next-box strong{font-size:12px;display:block}.dt-next-box span{font-size:11px;color:#83958f;display:block;margin-top:3px}.dt-add{width:100%;border:1px dashed #b6cfc5;border-radius:11px;background:#f5faf7;color:#236866;font:600 12px 'DM Sans';padding:12px;cursor:pointer;margin-top:12px}.dt-composer{border-top:1px solid #e2ece7;padding:14px 12px;display:flex;gap:8px;align-items:center}.dt-composer input{flex:1;border:1px solid #c9ddd5;border-radius:9px;padding:10px;font:12px 'DM Sans';outline:none}.dt-composer button{border:0;border-radius:9px;background:#236866;color:#fff;padding:10px 14px;font:600 12px 'DM Sans';cursor:pointer}.dt-toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:#143f40;color:#fff;padding:11px 15px;border-radius:10px;font-size:12px;box-shadow:0 8px 22px #143f4033;z-index:20}
      @media(max-width:800px){.dt-sidebar{display:none}.dt-menu{display:block}.dt-grid{grid-template-columns:1fr}.dt-welcome{align-items:flex-start;flex-direction:column}.dt-date{text-align:left}.dt-content{padding-top:28px}}@media(max-width:480px){.dt-topbar{height:65px}.dt-crumb{display:none}.dt-task{grid-template-columns:43px 32px 1fr 25px;gap:7px;padding-left:4px;padding-right:4px}.dt-hero{padding:19px}}
    `}</style>
    <aside className="dt-sidebar"><div className="dt-brand"><span className="dt-brand-mark"><PawPrint size={17}/></span><span>AgathaTrack</span></div><div className="dt-nav-label">Workspace</div>
      {([['Today',Home],['Health log',HeartPulse],['Appointments',CalendarDays],['Pet profiles',PawPrint]] as const).map(([label,NavIcon])=><button key={label} className={`dt-nav ${tab===label?'active':''}`} onClick={()=>{setTab(label);toast(`${label} view selected`)}}><NavIcon size={17} strokeWidth={1.8}/>{label}</button>)}
      <div className="dt-nav-label" style={{marginTop:27}}>Account</div><button className="dt-nav" onClick={()=>toast('Settings are ready to personalize')}><Settings2 size={17} strokeWidth={1.8}/>Settings</button>
      <div className="dt-sidebar-foot"><div style={{display:'flex',alignItems:'center',gap:10,padding:'0 9px'}}><div className="dt-avatar" style={{background:'#a66f42'}}>JM</div><div><div style={{fontSize:12,fontWeight:600}}>Jordan Miller</div><div style={{fontSize:10,color:'#86a7a2',marginTop:2}}>Guardian account</div></div></div></div>
    </aside>
    <section className="dt-main"><header className="dt-topbar"><button className="dt-menu" onClick={()=>toast('Navigation menu')}><Menu size={21}/></button><div className="dt-crumb"><span>Workspace</span><ChevronRight size={13}/><strong>{tab}</strong></div><div className="dt-top-actions"><button className="dt-icon-button" onClick={()=>toast('No new notifications')}><Bell size={17}/></button><button className="dt-avatar" style={{background:'#a66f42',border:0,cursor:'pointer'}} onClick={()=>toast('Profile menu opened')}>JM</button></div></header>
      <div className="dt-content"><div className="dt-welcome"><div><div className="dt-eyebrow">Tuesday · 14 May 2024</div><h1 className="dt-h1">Good morning, <em>Jordan.</em></h1></div><div className="dt-date"><b>One small check-in at a time.</b>Miso's daily care plan</div></div>
        <div className="dt-grid"><div style={{display:'flex',flexDirection:'column',gap:22}}><article className="dt-card dt-hero"><div className="dt-pet-select"><button className="dt-pet-button" onClick={()=>setShowPetMenu(!showPetMenu)}><span className="dt-pet-photo" style={{background:pet.tone}}>{pet.initials}</span><span><span className="dt-pet-name">{pet.name} <ChevronDown size={15} style={{verticalAlign:'-2px'}}/></span><span className="dt-pet-meta">{pet.species} · <span style={{color:'#29716d'}}>● {pet.status}</span></span></span></button><button className="dt-icon-button" style={{background:'#e9f1ec',borderColor:'#c9ddd5'}} onClick={()=>toast('Pet profile opened')}><MoreHorizontal size={18}/></button></div>
          {showPetMenu&&<div className="dt-pet-menu">{petData.map((p,i)=><button key={p.name} onClick={()=>{setActivePet(i);setShowPetMenu(false);toast(`${p.name}'s dashboard selected`)}}>{p.name} <span style={{color:'#9aa9a4'}}>· {p.species.split(' · ')[0]}</span></button>)}</div>}<div className="dt-health"><div><div className="dt-health-label">Weekly wellness</div><div className="dt-health-score">82 <small>/ 100</small></div><div style={{fontSize:11,color:'#5c7b76',marginTop:4}}>Looking steady this week</div></div><div className="dt-ring"><span>82%</span></div></div><div className="dt-progress"><i/></div></article>
          <article className="dt-card"><div className="dt-card-head"><div><div className="dt-eyebrow" style={{marginBottom:5}}>Daily plan</div><div className="dt-card-title">{completed} of {tasks.length} check-ins complete</div></div><button className="dt-card-link" onClick={()=>toast('Showing full health log')}>View log <ChevronRight size={12} style={{verticalAlign:'-2px'}}/></button></div><div className="dt-tasks">{tasks.map(task=><div className={`dt-task ${task.done?'is-done':''}`} key={task.id}><span className="dt-task-time">{task.time}</span><IconTile kind={task.kind}/><span><span className="dt-task-title">{task.title}</span><span className="dt-task-detail">{task.detail}</span></span><button className={`dt-check ${task.done?'checked':''}`} onClick={()=>{toggleTask(task.id);toast(task.done?'Check-in reopened':'Check-in recorded')}} aria-label={`Mark ${task.title} ${task.done?'incomplete':'complete'}`}>{task.done&&<Check size={14}/>}</button></div>)}</div>{showComposer?<div className="dt-composer"><input autoFocus placeholder="e.g. Nail trim at 18:00" onKeyDown={e=>{if(e.key==='Enter'){setShowComposer(false);toast('Care note added')}}}/><button onClick={()=>{setShowComposer(false);toast('Care note added')}}>Add</button><button onClick={()=>setShowComposer(false)} style={{background:'#e5eee9',color:'#52746e',padding:10}}><X size={14}/></button></div>:<div style={{padding:'0 23px 19px'}}><button className="dt-add" onClick={()=>setShowComposer(true)}><Plus size={14} style={{verticalAlign:'-3px',marginRight:5}}/>Add a care note</button></div>}</article></div>
          <div className="dt-side-stack"><article className="dt-card dt-stat-card"><div className="dt-stat-row"><div><div className="dt-eyebrow" style={{marginBottom:8}}>Hydration · today</div><div className="dt-stat-main">620 <small>/ 800 ml</small></div><div className="dt-stat-note">78% of daily target</div></div><span className="dt-stat-icon"><Droplets size={18}/></span></div><div className="dt-mini-chart">{[34,48,28,62,48,72].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div style={{fontSize:10,color:'#8b9d97',display:'flex',justifyContent:'space-between',marginTop:7}}><span>6 am</span><span>now</span></div></article>
            <article className="dt-card dt-next"><div className="dt-card-head" style={{padding:0}}><div><div className="dt-eyebrow" style={{marginBottom:5}}>Next appointment</div><div className="dt-card-title">Annual wellness exam</div></div><Stethoscope size={20} color="#a66f42"/></div><div className="dt-next-box"><CalendarDays size={17} color="#a66f42"/><div><strong>Thursday, 23 May</strong><span>10:30 · Cedar Grove Vet</span></div></div><button className="dt-add" onClick={()=>toast('Appointment details opened')}>View appointment <ChevronRight size={13} style={{verticalAlign:'-2px'}}/></button></article>
            <article className="dt-card" style={{padding:'20px 22px',background:'#e5eee6',borderColor:'#cfe0d5'}}><div style={{display:'flex',gap:11,alignItems:'flex-start'}}><ShieldCheck size={20} color="#29716d"/><div><div style={{fontSize:13,fontWeight:700,color:'#315f58'}}>Everything looks on track</div><div style={{fontSize:11,color:'#66857c',lineHeight:1.5,marginTop:5}}>Miso's routine is 3 days stronger than last week.</div></div></div></article>
          </div></div></div></section>{notice&&<div className="dt-toast"><Sparkles size={13} style={{verticalAlign:'-2px',marginRight:7,color:'#d3a069'}}/>{notice}</div>}
  </main>;
}