import React, { useState } from 'react';
import {
  Activity, Bell, CalendarDays, Check, ChevronRight, Clock3, Droplets, HeartPulse,
  Home, Menu, PawPrint, Pill, Plus, Settings2, ShieldCheck, Sparkles, Stethoscope, X,
} from 'lucide-react';

type Task = { id: number; time: string; title: string; detail: string; kind: 'medicine' | 'care' | 'walk'; done: boolean };
const initialTasks: Task[] = [
  { id: 1, time: '08:00', title: 'Breakfast + probiotic', detail: '1 scoop · with food', kind: 'medicine', done: true },
  { id: 2, time: '12:30', title: 'Midday water check', detail: 'Target 220 ml', kind: 'care', done: false },
  { id: 3, time: '17:45', title: 'Evening walk', detail: '20–30 minutes · gentle pace', kind: 'walk', done: false },
  { id: 4, time: '21:00', title: 'Joint supplement', detail: '1 chew · after dinner', kind: 'medicine', done: false },
];
const pets = [
  { name: 'Miso', species: 'Shiba Inu · 4 yr', initials: 'MI', tone: '#c4a17b', status: 'Doing well' },
  { name: 'Basil', species: 'Tabby cat · 2 yr', initials: 'BA', tone: '#879d7a', status: 'All caught up' },
];

function TaskIcon({ kind }: { kind: Task['kind'] }) {
  const Icon = kind === 'medicine' ? Pill : kind === 'walk' ? Activity : Droplets;
  return <span className={`od-task-icon od-${kind}`}><Icon size={16} /></span>;
}

export default function GuardianLayoutOperationsDesk() {
  const [activePet, setActivePet] = useState(0);
  const [tasks, setTasks] = useState(initialTasks);
  const [tab, setTab] = useState('Today');
  const [composer, setComposer] = useState(false);
  const [notice, setNotice] = useState('');
  const pet = pets[activePet];
  const completed = tasks.filter((task) => task.done).length;
  const toast = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2300); };
  const toggleTask = (id: number) => setTasks((current) => current.map((task) => task.id === id ? { ...task, done: !task.done } : task));

  return (
    <main className="od-shell">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Mono:wght@400;700&display=swap');
        .od-shell{min-height:100vh;background:#f1f3ee;color:#354239;font-family:'DM Sans',sans-serif;display:flex}
        .od-sidebar{width:210px;flex:0 0 210px;background:#35483f;color:#eef0e7;padding:22px 14px;display:flex;flex-direction:column}.od-brand{display:flex;align-items:center;gap:9px;padding:0 10px 28px;font-weight:700;letter-spacing:-.04em}.od-mark{width:29px;height:29px;border-radius:9px;background:#d5a83f;color:#35483f;display:grid;place-items:center}.od-label{font-size:9px;letter-spacing:.16em;text-transform:uppercase;color:#aeb9ad;margin:7px 11px 8px}.od-nav{display:flex;align-items:center;gap:10px;border:0;background:transparent;color:#bdc8bd;width:100%;padding:10px 11px;border-radius:9px;text-align:left;font:500 12px 'DM Sans';cursor:pointer}.od-nav:hover,.od-nav.active{background:#566b5d;color:#fff}.od-account{margin-top:auto;border-top:1px solid #58695d;padding:17px 8px 0;display:flex;gap:9px;align-items:center}.od-avatar{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:#718d76;color:#fff;font-size:10px;font-weight:700}
        .od-main{min-width:0;flex:1}.od-top{height:68px;background:#fbfcf8;border-bottom:1px solid #dce4da;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(18px,3.5vw,48px)}.od-mobile{display:none;border:0;background:none;color:#35483f}.od-context{font-size:12px;color:#8d978e}.od-context strong{color:#46584c;font-weight:700}.od-actions{display:flex;gap:10px;align-items:center}.od-icon-btn{width:35px;height:35px;border:1px solid #d6dfd5;background:#fbfcf8;border-radius:9px;color:#65766a;display:grid;place-items:center;cursor:pointer}
        .od-content{max-width:1180px;margin:auto;padding:31px clamp(18px,3.5vw,48px) 55px}.od-heading{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:24px}.od-kicker{color:#788b7c;font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.17em;margin-bottom:8px}.od-heading h1{margin:0;color:#304137;font-size:34px;letter-spacing:-.06em;line-height:1}.od-heading h1 em{color:#6e896f;font-style:normal}.od-date{font-family:'Space Mono',monospace;color:#7b867d;font-size:10px;line-height:1.6;text-align:right}.od-date b{color:#536657;display:block;font-size:11px}
        .od-petbar{display:flex;align-items:center;justify-content:space-between;background:#e6d7a8;border:1px solid #d6c484;border-radius:13px;padding:10px 14px;margin-bottom:18px}.od-pets{display:flex;gap:8px}.od-pet{display:flex;gap:8px;align-items:center;border:1px solid transparent;background:transparent;border-radius:9px;padding:6px 10px;color:#53604c;cursor:pointer;text-align:left;font:500 12px 'DM Sans'}.od-pet.selected{background:#f7f2df;border-color:#cdbd78;color:#35483f}.od-pet-dot{width:27px;height:27px;border-radius:8px;color:#fff;display:grid;place-items:center;font-size:9px;font-weight:700}.od-pet small{display:block;color:#7c785f;font-size:9px;margin-top:2px}.od-scope{font-size:10px;color:#756d4b;padding-right:5px}
        .od-layout{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(275px,.75fr);gap:18px}.od-card{background:#fbfcf8;border:1px solid #dce4da;border-radius:14px;box-shadow:0 6px 18px rgba(48,70,57,.045)}.od-card-head{display:flex;align-items:center;justify-content:space-between;padding:18px 20px 13px}.od-title{font-size:14px;font-weight:700;color:#3c4d42}.od-sub{font-size:10px;color:#8b968c;margin-top:3px}.od-link{border:0;background:none;color:#66816c;font:600 10px 'DM Sans';cursor:pointer}
        .od-queue{padding:0 10px 10px}.od-item{display:grid;grid-template-columns:52px 34px 1fr auto;align-items:center;gap:10px;border-top:1px solid #e7ece5;padding:13px 10px}.od-time{font:10px 'Space Mono',monospace;color:#8e9990}.od-task-icon{width:31px;height:31px;border-radius:9px;display:grid;place-items:center}.od-medicine{background:#f3e2c8;color:#a87323}.od-care{background:#e0ede3;color:#668d70}.od-walk{background:#e5ece7;color:#718b78}.od-item strong{font-size:12px;color:#4a5b4f;display:block}.od-item.is-done strong{text-decoration:line-through;color:#a3ada5}.od-item span.detail{font-size:10px;color:#969f98;display:block;margin-top:3px}.od-check{width:22px;height:22px;border-radius:7px;border:1px solid #ced9cf;background:#fbfcf8;color:transparent;display:grid;place-items:center;cursor:pointer}.od-check.checked{background:#718d76;border-color:#718d76;color:#fff}.od-add{border:1px dashed #bcae7b;background:#f8f4e8;color:#617b67;width:100%;padding:10px;border-radius:9px;font:600 11px 'DM Sans';cursor:pointer;margin-top:10px}.od-composer{display:flex;gap:6px;padding:12px 10px;border-top:1px solid #e6ebe4}.od-composer input{min-width:0;flex:1;border:1px solid #d4ddd4;border-radius:8px;padding:9px;font:11px 'DM Sans';outline:none}.od-composer button{border:0;border-radius:8px;background:#718d76;color:#fff;padding:9px 12px;font:600 11px 'DM Sans';cursor:pointer}
        .od-rail{display:flex;flex-direction:column;gap:18px}.od-health{padding:19px 20px;background:#e5efe7;border-color:#d2e1d6}.od-health-row{display:flex;justify-content:space-between;align-items:center}.od-health-num{font-size:29px;letter-spacing:-.06em;font-weight:700;color:#3b493e}.od-health-num small{font-size:11px;color:#89958b;letter-spacing:0}.od-ring{width:62px;height:62px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(#718d76 0 82%,#c6dac9 82%);position:relative;color:#52725a;font-size:13px;font-weight:700}.od-ring:after{content:'';position:absolute;inset:6px;border-radius:50%;background:#e5efe7}.od-ring span{position:relative;z-index:1}.od-rule{height:5px;border-radius:8px;background:#c7dac9;margin-top:15px;overflow:hidden}.od-rule i{display:block;width:82%;height:100%;background:#718d76}.od-metric{padding:18px 20px}.od-metric-row{display:flex;justify-content:space-between;align-items:center}.od-metric-value{font-size:25px;font-weight:700;letter-spacing:-.05em;color:#3e5045}.od-metric-value small{font-size:11px;color:#8e9990;letter-spacing:0}.od-metric-icon{color:#a87323;background:#f3e2c8;border-radius:9px;width:31px;height:31px;display:grid;place-items:center}.od-bars{height:39px;display:flex;align-items:flex-end;gap:6px;margin-top:16px}.od-bars i{flex:1;background:#c1d5c5;border-radius:4px 4px 1px 1px}.od-bars i:nth-child(4),.od-bars i:last-child{background:#718d76}
        .od-next{padding:18px 20px}.od-next-box{display:flex;gap:10px;align-items:center;background:#f0ecd9;border-radius:9px;padding:11px;margin-top:13px}.od-next-box strong{font-size:11px;display:block}.od-next-box span{font-size:10px;color:#918d80;display:block;margin-top:3px}.od-status{display:flex;gap:9px;padding:17px 20px;color:#48634f;background:#f5edcf;border-color:#dfd19e}.od-toast{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#35483f;color:#fff;padding:10px 14px;border-radius:9px;font-size:11px;z-index:10}
        @media(max-width:820px){.od-sidebar{display:none}.od-mobile{display:block}.od-layout{grid-template-columns:1fr}.od-heading{align-items:flex-start;flex-direction:column;gap:10px}.od-date{text-align:left}.od-content{padding-top:25px}}@media(max-width:500px){.od-top{height:62px}.od-context{display:none}.od-heading h1{font-size:30px}.od-petbar{align-items:flex-start;flex-direction:column;gap:8px}.od-pets{width:100%}.od-pet{flex:1;padding-left:6px}.od-scope{padding-left:5px}.od-item{grid-template-columns:44px 31px 1fr 22px;gap:7px;padding-left:4px;padding-right:4px}}
      `}</style>
      <aside className="od-sidebar">
        <div className="od-brand"><span className="od-mark"><PawPrint size={16} /></span>AgathaTrack</div>
        <div className="od-label">Coordination desk</div>
        {([['Today', Home], ['Health log', HeartPulse], ['Appointments', CalendarDays], ['Pet profiles', PawPrint]] as const).map(([label, Icon]) => <button key={label} className={`od-nav ${tab === label ? 'active' : ''}`} onClick={() => { setTab(label); toast(`${label} view selected`); }}><Icon size={16} />{label}</button>)}
        <div className="od-label" style={{ marginTop: 25 }}>Account</div><button className="od-nav" onClick={() => toast('Settings are ready to personalize')}><Settings2 size={16} />Settings</button>
        <div className="od-account"><div className="od-avatar">JM</div><div><div style={{ fontSize: 11, fontWeight: 600 }}>Jordan Miller</div><div style={{ fontSize: 9, color: '#aeb8ae', marginTop: 2 }}>Guardian account</div></div></div>
      </aside>
      <section className="od-main">
        <header className="od-top"><button className="od-mobile" onClick={() => toast('Navigation menu')}><Menu size={20} /></button><div className="od-context">Workspace <ChevronRight size={12} style={{ verticalAlign: '-2px' }} /> <strong>{tab}</strong></div><div className="od-actions"><button className="od-icon-btn" onClick={() => toast('No new notifications')} aria-label="Notifications"><Bell size={16} /></button><button className="od-avatar" style={{ border: 0, cursor: 'pointer' }} onClick={() => toast('Profile menu opened')} aria-label="Open profile">JM</button></div></header>
        <div className="od-content">
          <div className="od-heading"><div><div className="od-kicker">Tuesday · 14 May 2024 / operations view</div><h1>Today, <em>at a glance.</em></h1></div><div className="od-date"><b>3 actions remain</b> Miso's care plan · last synced 09:42</div></div>
          <div className="od-petbar"><div className="od-pets">{pets.map((p, i) => <button key={p.name} className={`od-pet ${activePet === i ? 'selected' : ''}`} onClick={() => { setActivePet(i); toast(`${p.name}'s dashboard selected`); }}><span className="od-pet-dot" style={{ background: p.tone }}>{p.initials}</span><span><b>{p.name}</b><small>{p.status}</small></span></button>)}</div><div className="od-scope"><ShieldCheck size={13} style={{ verticalAlign: '-3px', marginRight: 4 }} />Personal care · {pet.name}</div></div>
          <div className="od-layout"><div className="od-card"><div className="od-card-head"><div><div className="od-kicker" style={{ marginBottom: 5 }}>Action queue</div><div className="od-title">{completed} of {tasks.length} check-ins complete</div><div className="od-sub">The next thing to do, in order.</div></div><button className="od-link" onClick={() => toast('Showing full health log')}>View full log <ChevronRight size={11} style={{ verticalAlign: '-2px' }} /></button></div><div className="od-queue">{tasks.map((task) => <div className={`od-item ${task.done ? 'is-done' : ''}`} key={task.id}><span className="od-time">{task.time}</span><TaskIcon kind={task.kind} /><span><strong>{task.title}</strong><span className="detail">{task.detail}</span></span><button className={`od-check ${task.done ? 'checked' : ''}`} onClick={() => { toggleTask(task.id); toast(task.done ? 'Check-in reopened' : 'Check-in recorded'); }} aria-label={`${task.done ? 'Reopen' : 'Complete'} ${task.title}`}>{task.done && <Check size={13} />}</button></div>)}{composer ? <div className="od-composer"><input autoFocus placeholder="e.g. Nail trim at 18:00" onKeyDown={(e) => { if (e.key === 'Enter') { setComposer(false); toast('Care note added'); } }} /><button onClick={() => { setComposer(false); toast('Care note added'); }}>Add</button><button onClick={() => setComposer(false)} style={{ background: '#e8ece6', color: '#627b68' }} aria-label="Cancel"><X size={13} /></button></div> : <button className="od-add" onClick={() => setComposer(true)}><Plus size={13} style={{ verticalAlign: '-3px', marginRight: 4 }} /> Add a care note</button>}</div></div>
            <div className="od-rail"><article className="od-card od-health"><div className="od-kicker">Wellness signal</div><div className="od-health-row"><div><div className="od-health-num">82 <small>/ 100</small></div><div className="od-sub">Steady this week</div></div><div className="od-ring"><span>82%</span></div></div><div className="od-rule"><i /></div></article><article className="od-card od-metric"><div className="od-kicker">Hydration · today</div><div className="od-metric-row"><div><div className="od-metric-value">620 <small>/ 800 ml</small></div><div className="od-sub">78% of daily target</div></div><span className="od-metric-icon"><Droplets size={16} /></span></div><div className="od-bars">{[34,48,28,62,48,72].map((h, i) => <i key={i} style={{ height: `${h}%` }} />)}</div></article><article className="od-card od-next"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div><div className="od-kicker" style={{ marginBottom: 5 }}>Next appointment</div><div className="od-title">Annual wellness exam</div></div><Stethoscope size={18} color="#718d76" /></div><div className="od-next-box"><CalendarDays size={16} color="#718d76" /><div><strong>Thursday, 23 May</strong><span>10:30 · Cedar Grove Vet</span></div></div><button className="od-link" style={{ padding: '12px 0 0' }} onClick={() => toast('Appointment details opened')}>Open appointment <ChevronRight size={11} style={{ verticalAlign: '-2px' }} /></button></article><article className="od-card od-status"><Sparkles size={17} color="#a87323" /><div><div style={{ fontSize: 12, fontWeight: 700 }}>No handoffs waiting</div><div style={{ fontSize: 10, lineHeight: 1.45, marginTop: 4, color: '#718878' }}>Miso's routine is 3 days stronger than last week.</div></div></article></div>
          </div>
        </div>
      </section>
      {notice && <div className="od-toast"><Clock3 size={12} style={{ verticalAlign: '-2px', marginRight: 6, color: '#d5a83f' }} />{notice}</div>}
    </main>
  );
}