import React, { useState } from 'react';
import {
  Activity, Bell, CalendarDays, Check, ChevronDown, ChevronRight, Droplets,
  HeartPulse, Home, Menu, MoreHorizontal, PawPrint, Pill, Plus, Settings2,
  ShieldCheck, Sparkles, Stethoscope, X,
} from 'lucide-react';

type Task = { id: number; time: string; title: string; detail: string; kind: 'medicine' | 'care' | 'walk'; done: boolean };
const initialTasks: Task[] = [
  { id: 1, time: '08:00', title: 'Breakfast + probiotic', detail: '1 scoop · with food', kind: 'medicine', done: true },
  { id: 2, time: '12:30', title: 'Midday water check', detail: 'Target 220 ml', kind: 'care', done: false },
  { id: 3, time: '17:45', title: 'Evening walk', detail: '20–30 minutes · gentle pace', kind: 'walk', done: false },
  { id: 4, time: '21:00', title: 'Joint supplement', detail: '1 chew · after dinner', kind: 'medicine', done: false },
];
const petData = [
  { name: 'Miso', species: 'Shiba Inu · 4 yr', initials: 'MI', tone: '#b86e4d', status: 'Doing well' },
  { name: 'Basil', species: 'Tabby cat · 2 yr', initials: 'BA', tone: '#5b8f8a', status: 'All caught up' },
];

function IconTile({ kind }: { kind: Task['kind'] }) {
  const Icon = kind === 'medicine' ? Pill : kind === 'walk' ? Activity : Droplets;
  return <span className={`ho-icon ho-${kind}`}><Icon size={17} strokeWidth={1.8} /></span>;
}

export default function GuardianShelterHarbourOchre() {
  const [activePet, setActivePet] = useState(0);
  const [tasks, setTasks] = useState(initialTasks);
  const [tab, setTab] = useState('Today');
  const [showPetMenu, setShowPetMenu] = useState(false);
  const [showComposer, setShowComposer] = useState(false);
  const [notice, setNotice] = useState('');
  const pet = petData[activePet];
  const completed = tasks.filter((task) => task.done).length;
  const toast = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2400); };
  const toggleTask = (id: number) => setTasks((current) => current.map((task) => task.id === id ? { ...task, done: !task.done } : task));

  return <main className="ho-shell">
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500&display=swap');
      .ho-shell{min-height:100vh;background:#edf3f1;color:#243d3d;font-family:'DM Sans',sans-serif;display:flex}
      .ho-sidebar{width:226px;flex:0 0 226px;background:#173c3d;color:#edf5f2;padding:25px 16px 20px;display:flex;flex-direction:column}
      .ho-brand{display:flex;align-items:center;gap:10px;padding:0 10px 32px;font-weight:700;letter-spacing:-.03em}.ho-brand-mark{width:30px;height:30px;border-radius:10px;background:#d39b45;display:grid;place-items:center;color:#173c3d}
      .ho-nav-label{color:#9ab6af;font-size:10px;letter-spacing:.14em;text-transform:uppercase;margin:8px 12px 10px}.ho-nav{display:flex;align-items:center;gap:11px;width:100%;border:0;background:none;color:#abc5bf;padding:11px 12px;border-radius:11px;text-align:left;font:500 13px 'DM Sans';cursor:pointer}.ho-nav.active{color:#f9fbf9;background:#286161}.ho-nav:hover{background:#225354;color:#fff}.ho-sidebar-foot{margin-top:auto;border-top:1px solid #315c5b;padding-top:18px}
      .ho-main{min-width:0;flex:1}.ho-topbar{height:78px;background:#f9fbf8;border-bottom:1px solid #d8e4df;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(20px,4vw,56px)}.ho-menu{display:none;border:0;background:none;color:#173c3d}.ho-crumb{font-size:12px;color:#7d9791;display:flex;gap:8px;align-items:center}.ho-crumb strong{color:#345b58}.ho-top-actions{display:flex;gap:12px;align-items:center}.ho-icon-button{width:38px;height:38px;border:1px solid #d3e1dc;background:#fff;border-radius:11px;display:grid;place-items:center;color:#587b76;cursor:pointer}.ho-avatar{width:37px;height:37px;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:11px;font-weight:700}
      .ho-content{max-width:1120px;margin:0 auto;padding:43px clamp(20px,4vw,56px) 60px}.ho-welcome{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:32px}.ho-eyebrow{color:#9a6b26;text-transform:uppercase;letter-spacing:.15em;font-size:10px;font-weight:700;margin-bottom:10px}.ho-h1{font-size:clamp(28px,4vw,40px);line-height:1.05;letter-spacing:-.055em;margin:0;color:#224140}.ho-h1 em{font-family:Fraunces,serif;font-weight:500;color:#327a78;font-style:normal}.ho-date{color:#728c87;font-size:13px;text-align:right;line-height:1.5}.ho-date b{color:#395f5c;display:block;font-size:14px}
      .ho-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(260px,.8fr);gap:22px}.ho-card{background:#fbfdfb;border:1px solid #d8e4df;border-radius:18px;box-shadow:0 8px 24px rgba(35,73,69,.07)}.ho-hero{padding:24px;background:#dcebe7;border-color:#c6dcd5;position:relative;overflow:hidden}.ho-hero:after{content:'';position:absolute;right:-55px;top:-75px;width:220px;height:220px;border-radius:50%;border:1px solid rgba(50,122,120,.24);box-shadow:0 0 0 22px rgba(50,122,120,.07),0 0 0 44px rgba(182,126,49,.06)}
      .ho-pet-select{position:relative;z-index:2;display:flex;align-items:center;justify-content:space-between}.ho-pet-button{display:flex;align-items:center;gap:12px;background:none;border:0;padding:0;cursor:pointer;color:#254745;text-align:left}.ho-pet-photo{width:54px;height:54px;border-radius:17px;display:grid;place-items:center;color:#fff;font-weight:700;letter-spacing:.06em;box-shadow:inset 0 0 0 4px rgba(255,255,255,.3)}.ho-pet-name{font-weight:700;font-size:20px;letter-spacing:-.04em;display:block}.ho-pet-meta{color:#52726e;font-size:12px;display:block;margin-top:2px}.ho-pet-menu{position:absolute;right:24px;top:84px;background:#fbfdfb;border:1px solid #d5e1dc;border-radius:12px;padding:5px;box-shadow:0 12px 30px #2349431a;z-index:5;min-width:150px}.ho-pet-menu button{width:100%;border:0;background:none;padding:9px;text-align:left;border-radius:8px;color:#496863;cursor:pointer;font:500 12px 'DM Sans'}.ho-pet-menu button:hover{background:#e8f1ed}
      .ho-health{margin-top:27px;display:flex;align-items:flex-end;justify-content:space-between;position:relative;z-index:1}.ho-health-label{color:#557570;font-size:12px;margin-bottom:7px}.ho-health-score{font-size:37px;letter-spacing:-.06em;font-weight:700;color:#284b49}.ho-health-score small{font-size:14px;color:#78928c;font-weight:500;letter-spacing:0}.ho-ring{width:91px;height:91px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(#327a78 0 82%,#b9d3cc 82% 100%);position:relative}.ho-ring:after{content:'';position:absolute;inset:8px;background:#dcebe7;border-radius:50%}.ho-ring span{position:relative;z-index:1;font-size:18px;font-weight:700;color:#2e6664}.ho-progress{height:5px;background:#b9d3cc;border-radius:9px;margin-top:17px;overflow:hidden;position:relative;z-index:1}.ho-progress i{display:block;width:82%;height:100%;background:#327a78;border-radius:9px}
      .ho-card-head{display:flex;align-items:center;justify-content:space-between;padding:21px 23px 14px}.ho-card-title{font-size:15px;font-weight:700;letter-spacing:-.02em}.ho-card-link{color:#a66d25;border:0;background:none;font:600 11px 'DM Sans';cursor:pointer}.ho-tasks{padding:0 12px 10px}.ho-task{display:grid;grid-template-columns:50px 35px 1fr 28px;align-items:center;gap:10px;padding:13px 11px;border-top:1px solid #e8efec}.ho-task-time{font-size:11px;color:#829b96;font-variant-numeric:tabular-nums}.ho-icon{width:33px;height:33px;border-radius:10px;display:grid;place-items:center}.ho-medicine{background:#f3e6d4;color:#ad742c}.ho-care{background:#dcece8;color:#367b78}.ho-walk{background:#e4ece8;color:#597c76}.ho-task-title{font-size:13px;font-weight:600;color:#385652;display:block}.ho-task-detail{font-size:11px;color:#879d98;margin-top:3px;display:block}.ho-task.is-done .ho-task-title{text-decoration:line-through;color:#9caaa6}.ho-check{width:23px;height:23px;border:1px solid #cbdcd6;border-radius:50%;background:#fff;display:grid;place-items:center;color:transparent;cursor:pointer}.ho-check.checked{background:#327a78;border-color:#327a78;color:#fff}
      .ho-stat-card{padding:22px 23px}.ho-stat-row{display:flex;justify-content:space-between;align-items:center}.ho-stat-main{font-size:30px;font-weight:700;letter-spacing:-.05em;color:#2c514e}.ho-stat-main small{font-size:12px;font-weight:500;color:#849a95;letter-spacing:0}.ho-stat-note{font-size:11px;color:#809792;margin-top:5px}.ho-stat-icon{width:37px;height:37px;border-radius:12px;background:#dcece8;color:#327a78;display:grid;place-items:center}.ho-mini-chart{display:flex;align-items:flex-end;gap:7px;height:53px;margin-top:22px}.ho-mini-chart i{flex:1;background:#b9d5ce;border-radius:5px 5px 2px 2px;min-height:15px}.ho-mini-chart i:nth-child(4),.ho-mini-chart i:last-child{background:#327a78}.ho-side-stack{display:flex;flex-direction:column;gap:22px}.ho-next{padding:22px 23px}.ho-next-box{background:#f3ecdf;border-radius:12px;padding:14px;margin-top:14px;display:flex;gap:11px;align-items:center}.ho-next-box strong{font-size:12px;display:block}.ho-next-box span{font-size:11px;color:#8e8879;display:block;margin-top:3px}.ho-add{width:100%;border:1px dashed #c7b185;border-radius:11px;background:#fcfaf4;color:#a66d25;font:600 12px 'DM Sans';padding:12px;cursor:pointer;margin-top:12px}.ho-composer{border-top:1px solid #e3ece8;padding:14px 12px;display:flex;gap:8px;align-items:center}.ho-composer input{flex:1;border:1px solid #d2e0db;border-radius:9px;padding:10px;font:12px 'DM Sans';outline:none}.ho-composer button{border:0;border-radius:9px;background:#327a78;color:#fff;padding:10px 14px;font:600 12px 'DM Sans';cursor:pointer}.ho-toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:#173c3d;color:#fff;padding:11px 15px;border-radius:10px;font-size:12px;box-shadow:0 8px 22px #173c3d33;z-index:20}
      @media(max-width:800px){.ho-sidebar{display:none}.ho-menu{display:block}.ho-grid{grid-template-columns:1fr}.ho-welcome{align-items:flex-start;flex-direction:column}.ho-date{text-align:left}.ho-content{padding-top:28px}}@media(max-width:480px){.ho-topbar{height:65px}.ho-crumb{display:none}.ho-task{grid-template-columns:43px 32px 1fr 25px;gap:7px;padding-left:4px;padding-right:4px}.ho-hero{padding:19px}}
    `}</style>
    <aside className="ho-sidebar"><div className="ho-brand"><span className="ho-brand-mark"><PawPrint size={17}/></span><span>AgathaTrack</span></div><div className="ho-nav-label">Workspace</div>
      {([['Today',Home],['Health log',HeartPulse],['Appointments',CalendarDays],['Pet profiles',PawPrint]] as const).map(([label,NavIcon])=><button key={label} className={`ho-nav ${tab===label?'active':''}`} onClick={()=>{setTab(label);toast(`${label} view selected`)}}><NavIcon size={17} strokeWidth={1.8}/>{label}</button>)}
      <div className="ho-nav-label" style={{marginTop:27}}>Account</div><button className="ho-nav" onClick={()=>toast('Settings are ready to personalize')}><Settings2 size={17} strokeWidth={1.8}/>Settings</button>
      <div className="ho-sidebar-foot"><div style={{display:'flex',alignItems:'center',gap:10,padding:'0 9px'}}><div className="ho-avatar" style={{background:'#b77832'}}>JM</div><div><div style={{fontSize:12,fontWeight:600}}>Jordan Miller</div><div style={{fontSize:10,color:'#9ab6af',marginTop:2}}>Guardian account</div></div></div></div>
    </aside>
    <section className="ho-main"><header className="ho-topbar"><button className="ho-menu" onClick={()=>toast('Navigation menu')}><Menu size={21}/></button><div className="ho-crumb"><span>Workspace</span><ChevronRight size={13}/><strong>{tab}</strong></div><div className="ho-top-actions"><button className="ho-icon-button" onClick={()=>toast('No new notifications')}><Bell size={17}/></button><button className="ho-avatar" style={{background:'#b77832',border:0,cursor:'pointer'}} onClick={()=>toast('Profile menu opened')}>JM</button></div></header>
      <div className="ho-content"><div className="ho-welcome"><div><div className="ho-eyebrow">Tuesday · 14 May 2024</div><h1 className="ho-h1">Good morning, <em>Jordan.</em></h1></div><div className="ho-date"><b>One small check-in at a time.</b>Miso's daily care plan</div></div>
        <div className="ho-grid"><div style={{display:'flex',flexDirection:'column',gap:22}}><article className="ho-card ho-hero"><div className="ho-pet-select"><button className="ho-pet-button" onClick={()=>setShowPetMenu(!showPetMenu)}><span className="ho-pet-photo" style={{background:pet.tone}}>{pet.initials}</span><span><span className="ho-pet-name">{pet.name} <ChevronDown size={15} style={{verticalAlign:'-2px'}}/></span><span className="ho-pet-meta">{pet.species} · <span style={{color:'#327a78'}}>● {pet.status}</span></span></span></button><button className="ho-icon-button" style={{background:'#eaf2ef',borderColor:'#c8ded6'}} onClick={()=>toast('Pet profile opened')}><MoreHorizontal size={18}/></button></div>
          {showPetMenu&&<div className="ho-pet-menu">{petData.map((p,i)=><button key={p.name} onClick={()=>{setActivePet(i);setShowPetMenu(false);toast(`${p.name}'s dashboard selected`)}}>{p.name} <span style={{color:'#94a6a1'}}>· {p.species.split(' · ')[0]}</span></button>)}</div>}<div className="ho-health"><div><div className="ho-health-label">Weekly wellness</div><div className="ho-health-score">82 <small>/ 100</small></div><div style={{fontSize:11,color:'#5d7d77',marginTop:4}}>Looking steady this week</div></div><div className="ho-ring"><span>82%</span></div></div><div className="ho-progress"><i/></div></article>
          <article className="ho-card"><div className="ho-card-head"><div><div className="ho-eyebrow" style={{marginBottom:5}}>Daily plan</div><div className="ho-card-title">{completed} of {tasks.length} check-ins complete</div></div><button className="ho-card-link" onClick={()=>toast('Showing full health log')}>View log <ChevronRight size={12} style={{verticalAlign:'-2px'}}/></button></div><div className="ho-tasks">{tasks.map(task=><div className={`ho-task ${task.done?'is-done':''}`} key={task.id}><span className="ho-task-time">{task.time}</span><IconTile kind={task.kind}/><span><span className="ho-task-title">{task.title}</span><span className="ho-task-detail">{task.detail}</span></span><button className={`ho-check ${task.done?'checked':''}`} onClick={()=>{toggleTask(task.id);toast(task.done?'Check-in reopened':'Check-in recorded')}} aria-label={`Mark ${task.title} ${task.done?'incomplete':'complete'}`}>{task.done&&<Check size={14}/>}</button></div>)}</div>{showComposer?<div className="ho-composer"><input autoFocus placeholder="e.g. Nail trim at 18:00" onKeyDown={e=>{if(e.key==='Enter'){setShowComposer(false);toast('Care note added')}}}/><button onClick={()=>{setShowComposer(false);toast('Care note added')}}>Add</button><button onClick={()=>setShowComposer(false)} style={{background:'#e9efec',color:'#55736e',padding:10}}><X size={14}/></button></div>:<div style={{padding:'0 23px 19px'}}><button className="ho-add" onClick={()=>setShowComposer(true)}><Plus size={14} style={{verticalAlign:'-3px',marginRight:5}}/>Add a care note</button></div>}</article></div>
          <div className="ho-side-stack"><article className="ho-card ho-stat-card"><div className="ho-stat-row"><div><div className="ho-eyebrow" style={{marginBottom:8}}>Hydration · today</div><div className="ho-stat-main">620 <small>/ 800 ml</small></div><div className="ho-stat-note">78% of daily target</div></div><span className="ho-stat-icon"><Droplets size={18}/></span></div><div className="ho-mini-chart">{[34,48,28,62,48,72].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div style={{fontSize:10,color:'#8ca19c',display:'flex',justifyContent:'space-between',marginTop:7}}><span>6 am</span><span>now</span></div></article>
            <article className="ho-card ho-next"><div className="ho-card-head" style={{padding:0}}><div><div className="ho-eyebrow" style={{marginBottom:5}}>Next appointment</div><div className="ho-card-title">Annual wellness exam</div></div><Stethoscope size={20} color="#a66d25"/></div><div className="ho-next-box"><CalendarDays size={17} color="#a66d25"/><div><strong>Thursday, 23 May</strong><span>10:30 · Cedar Grove Vet</span></div></div><button className="ho-add" onClick={()=>toast('Appointment details opened')}>View appointment <ChevronRight size={13} style={{verticalAlign:'-2px'}}/></button></article>
            <article className="ho-card" style={{padding:'20px 22px',background:'#f1eadc',borderColor:'#e4d8bd'}}><div style={{display:'flex',gap:11,alignItems:'flex-start'}}><ShieldCheck size={20} color="#a66d25"/><div><div style={{fontSize:13,fontWeight:700,color:'#665334'}}>Everything looks on track</div><div style={{fontSize:11,color:'#88795c',lineHeight:1.5,marginTop:5}}>Miso's routine is 3 days stronger than last week.</div></div></div></article>
          </div></div></div></section>{notice&&<div className="ho-toast"><Sparkles size={13} style={{verticalAlign:'-2px',marginRight:7,color:'#d39b45'}}/>{notice}</div>}
  </main>;
}