import React, { useState } from 'react';
import {
  Activity, Bell, CalendarDays, Check, ChevronDown, ChevronRight, Droplets,
  HeartPulse, Home, Menu, MoreHorizontal, PawPrint, Pill, Plus, Settings2,
  ShieldCheck, Sparkles, Stethoscope, X,
} from 'lucide-react';

type Task = { id: number; time: string; title: string; detail: string; kind: 'medicine' | 'care' | 'walk'; done: boolean };
const initialTasks: Task[] = [
  { id: 1, time: '08:00', title: 'Breakfast + probiotic', detail: '1 scoop · with food', kind: 'medicine', done: true },
  { id: 2, time: '12:30', title: 'Midday water check', detail: 'Target 220 ml', kind: 'care', done: false },
  { id: 3, time: '17:45', title: 'Evening walk', detail: '20–30 minutes · gentle pace', kind: 'walk', done: false },
  { id: 4, time: '21:00', title: 'Joint supplement', detail: '1 chew · after dinner', kind: 'medicine', done: false },
];
const petData = [
  { name: 'Miso', species: 'Shiba Inu · 4 yr', initials: 'MI', tone: '#c9a267', status: 'Doing well' },
  { name: 'Basil', species: 'Tabby cat · 2 yr', initials: 'BA', tone: '#88a694', status: 'All caught up' },
];
function IconTile({ kind }: { kind: Task['kind'] }) {
  const Icon = kind === 'medicine' ? Pill : kind === 'walk' ? Activity : Droplets;
  return <span className={`sg-icon sg-${kind}`}><Icon size={17} strokeWidth={1.8} /></span>;
}

export default function GuardianShelterSageGolden() {
  const [activePet, setActivePet] = useState(0);
  const [tasks, setTasks] = useState(initialTasks);
  const [tab, setTab] = useState('Today');
  const [showPetMenu, setShowPetMenu] = useState(false);
  const [showComposer, setShowComposer] = useState(false);
  const [notice, setNotice] = useState('');
  const pet = petData[activePet];
  const completed = tasks.filter((task) => task.done).length;
  const toast = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2400); };
  const toggleTask = (id: number) => setTasks((current) => current.map((task) => task.id === id ? { ...task, done: !task.done } : task));
  return <main className="sg-shell">
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500&display=swap');
      .sg-shell{min-height:100vh;background:#f4f5ef;color:#2d3934;font-family:'DM Sans',sans-serif;display:flex}
      .sg-sidebar{width:226px;flex:0 0 226px;background:#243b35;color:#f2f4e9;padding:25px 16px 20px;display:flex;flex-direction:column}
      .sg-brand{display:flex;align-items:center;gap:10px;padding:0 10px 32px;font-weight:700;letter-spacing:-.03em}.sg-brand-mark{width:30px;height:30px;border-radius:10px;background:#d6b064;display:grid;place-items:center;color:#243b35}
      .sg-nav-label{color:#9eb3a5;font-size:10px;letter-spacing:.14em;text-transform:uppercase;margin:8px 12px 10px}.sg-nav{display:flex;align-items:center;gap:11px;width:100%;border:0;background:none;color:#aec0b5;padding:11px 12px;border-radius:11px;text-align:left;font:500 13px 'DM Sans';cursor:pointer}.sg-nav.active{color:#fff;background:#3d5c4f}.sg-nav:hover{background:#345146;color:#fff}.sg-sidebar-foot{margin-top:auto;border-top:1px solid #476258;padding-top:18px}
      .sg-main{min-width:0;flex:1}.sg-topbar{height:78px;background:#fafbf7;border-bottom:1px solid #dfe6dc;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(20px,4vw,56px)}.sg-menu{display:none;border:0;background:none;color:#243b35}.sg-crumb{font-size:12px;color:#829087;display:flex;gap:8px;align-items:center}.sg-crumb strong{color:#34473e;font-weight:600}.sg-top-actions{display:flex;gap:12px;align-items:center}.sg-icon-button{width:38px;height:38px;border:1px solid #d9e2d7;background:#fff;border-radius:11px;display:grid;place-items:center;color:#61736a;cursor:pointer}.sg-avatar{width:37px;height:37px;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:11px;font-weight:700}
      .sg-content{max-width:1120px;margin:0 auto;padding:43px clamp(20px,4vw,56px) 60px}.sg-welcome{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:32px}.sg-eyebrow{color:#718e7e;text-transform:uppercase;letter-spacing:.15em;font-size:10px;font-weight:700;margin-bottom:10px}.sg-h1{font-size:clamp(28px,4vw,40px);line-height:1.05;letter-spacing:-.055em;margin:0;color:#263b32}.sg-h1 em{font-family:Fraunces,serif;font-weight:500;color:#5b8a70;font-style:normal}.sg-date{color:#78877e;font-size:13px;text-align:right;line-height:1.5}.sg-date b{color:#3d5649;display:block;font-size:14px}
      .sg-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(260px,.8fr);gap:22px}.sg-card{background:#fffefa;border:1px solid #dee6dc;border-radius:18px;box-shadow:0 8px 24px rgba(38,63,49,.05)}.sg-hero{padding:24px;background:#f1eddb;border-color:#e5dfc7;position:relative;overflow:hidden}.sg-hero:after{content:'';position:absolute;right:-55px;top:-75px;width:220px;height:220px;border-radius:50%;border:1px solid rgba(171,132,51,.2);box-shadow:0 0 0 22px rgba(171,132,51,.06),0 0 0 44px rgba(171,132,51,.035)}.sg-pet-select{position:relative;z-index:2;display:flex;align-items:center;justify-content:space-between}.sg-pet-button{display:flex;align-items:center;gap:12px;background:none;border:0;padding:0;cursor:pointer;color:#304338;text-align:left}.sg-pet-photo{width:54px;height:54px;border-radius:17px;display:grid;place-items:center;color:#fff;font-weight:700;letter-spacing:.06em;box-shadow:inset 0 0 0 4px rgba(255,255,255,.3)}.sg-pet-name{font-weight:700;font-size:20px;letter-spacing:-.04em;display:block}.sg-pet-meta{color:#7a806c;font-size:12px;display:block;margin-top:2px}.sg-pet-menu{position:absolute;right:24px;top:84px;background:#fffefa;border:1px solid #dce4d8;border-radius:12px;padding:5px;box-shadow:0 12px 30px #31483a1a;z-index:5;min-width:150px}.sg-pet-menu button{width:100%;border:0;background:none;padding:9px;text-align:left;border-radius:8px;color:#52645a;cursor:pointer;font:500 12px 'DM Sans'}.sg-pet-menu button:hover{background:#edf2e8}.sg-health{margin-top:27px;display:flex;align-items:flex-end;justify-content:space-between;position:relative;z-index:1}.sg-health-label{color:#7b806b;font-size:12px;margin-bottom:7px}.sg-health-score{font-size:37px;letter-spacing:-.06em;font-weight:700;color:#314439}.sg-health-score small{font-size:14px;color:#8b927f;font-weight:500;letter-spacing:0}.sg-ring{width:91px;height:91px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(#6b9679 0 82%,#d9ddc6 82% 100%);position:relative}.sg-ring:after{content:'';position:absolute;inset:8px;background:#f1eddb;border-radius:50%}.sg-ring span{position:relative;z-index:1;font-size:18px;font-weight:700;color:#4d765d}.sg-progress{height:5px;background:#d9dcc9;border-radius:9px;margin-top:17px;overflow:hidden;position:relative;z-index:1}.sg-progress i{display:block;width:82%;height:100%;background:#6b9679;border-radius:9px}
      .sg-card-head{display:flex;align-items:center;justify-content:space-between;padding:21px 23px 14px}.sg-card-title{font-size:15px;font-weight:700;letter-spacing:-.02em}.sg-card-link{color:#5b8a70;border:0;background:none;font:600 11px 'DM Sans';cursor:pointer}.sg-tasks{padding:0 12px 10px}.sg-task{display:grid;grid-template-columns:50px 35px 1fr 28px;align-items:center;gap:10px;padding:13px 11px;border-top:1px solid #e8eee6}.sg-task-time{font-size:11px;color:#8b9890;font-variant-numeric:tabular-nums}.sg-icon{width:33px;height:33px;border-radius:10px;display:grid;place-items:center}.sg-medicine{background:#f7e8dc;color:#c17b4b}.sg-care{background:#e1eee5;color:#4e8e6d}.sg-walk{background:#e5edf0;color:#648291}.sg-task-title{font-size:13px;font-weight:600;color:#405047;display:block}.sg-task-detail{font-size:11px;color:#929d96;margin-top:3px;display:block}.sg-task.is-done .sg-task-title{text-decoration:line-through;color:#a5afa9}.sg-check{width:23px;height:23px;border:1px solid #d2ddd3;border-radius:50%;background:#fff;display:grid;place-items:center;color:transparent;cursor:pointer}.sg-check.checked{background:#5b9474;border-color:#5b9474;color:#fff}.sg-stat-card{padding:22px 23px}.sg-stat-row{display:flex;justify-content:space-between;align-items:center}.sg-stat-main{font-size:30px;font-weight:700;letter-spacing:-.05em;color:#314439}.sg-stat-main small{font-size:12px;font-weight:500;color:#89958d;letter-spacing:0}.sg-stat-note{font-size:11px;color:#87948c;margin-top:5px}.sg-stat-icon{width:37px;height:37px;border-radius:12px;background:#e1eee5;color:#4e8e6d;display:grid;place-items:center}.sg-mini-chart{display:flex;align-items:flex-end;gap:7px;height:53px;margin-top:22px}.sg-mini-chart i{flex:1;background:#c4d9ca;border-radius:5px 5px 2px 2px;min-height:15px}.sg-mini-chart i:nth-child(4),.sg-mini-chart i:last-child{background:#5b9474}.sg-side-stack{display:flex;flex-direction:column;gap:22px}.sg-next{padding:22px 23px}.sg-next-box{background:#f1eee1;border-radius:12px;padding:14px;margin-top:14px;display:flex;gap:11px;align-items:center}.sg-next-box strong{font-size:12px;display:block}.sg-next-box span{font-size:11px;color:#8a9285;display:block;margin-top:3px}.sg-add{width:100%;border:1px dashed #c9cfb9;border-radius:11px;background:#fbfaf3;color:#618267;font:600 12px 'DM Sans';padding:12px;cursor:pointer;margin-top:12px}.sg-composer{border-top:1px solid #e6ece3;padding:14px 12px;display:flex;gap:8px;align-items:center}.sg-composer input{flex:1;border:1px solid #d7e0d6;border-radius:9px;padding:10px;font:12px 'DM Sans';outline:none}.sg-composer button{border:0;border-radius:9px;background:#5b8f70;color:#fff;padding:10px 14px;font:600 12px 'DM Sans';cursor:pointer}.sg-toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:#294239;color:#fff;padding:11px 15px;border-radius:10px;font-size:12px;box-shadow:0 8px 22px #29423933;z-index:20}
      @media(max-width:800px){.sg-sidebar{display:none}.sg-menu{display:block}.sg-grid{grid-template-columns:1fr}.sg-welcome{align-items:flex-start;flex-direction:column}.sg-date{text-align:left}.sg-content{padding-top:28px}}@media(max-width:480px){.sg-topbar{height:65px}.sg-crumb{display:none}.sg-task{grid-template-columns:43px 32px 1fr 25px;gap:7px;padding-left:4px;padding-right:4px}.sg-hero{padding:19px}}
    `}</style>
    <aside className="sg-sidebar"><div className="sg-brand"><span className="sg-brand-mark"><PawPrint size={17}/></span><span>AgathaTrack</span></div><div className="sg-nav-label">Workspace</div>
      {[[ 'Today', Home ], [ 'Health log', HeartPulse ], [ 'Appointments', CalendarDays ], [ 'Pet profiles', PawPrint ]].map(([label, NavIcon]) => <button key={label as string} className={`sg-nav ${tab === label ? 'active' : ''}`} onClick={() => { setTab(label as string); toast(`${label} view selected`); }}><NavIcon size={17} strokeWidth={1.8}/>{label as string}</button>)}
      <div className="sg-nav-label" style={{marginTop:27}}>Account</div><button className="sg-nav" onClick={() => toast('Settings are ready to personalize')}><Settings2 size={17} strokeWidth={1.8}/>Settings</button><div className="sg-sidebar-foot"><div style={{display:'flex',alignItems:'center',gap:10,padding:'0 9px'}}><div className="sg-avatar" style={{background:'#668b72'}}>JM</div><div><div style={{fontSize:12,fontWeight:600}}>Jordan Miller</div><div style={{fontSize:10,color:'#9eb3a5',marginTop:2}}>Guardian account</div></div></div></div>
    </aside>
    <section className="sg-main"><header className="sg-topbar"><button className="sg-menu" onClick={() => toast('Navigation menu')}><Menu size={21}/></button><div className="sg-crumb"><span>Workspace</span><ChevronRight size={13}/><strong>{tab}</strong></div><div className="sg-top-actions"><button className="sg-icon-button" onClick={() => toast('No new notifications')}><Bell size={17}/></button><button className="sg-avatar" style={{background:'#668b72',border:0,cursor:'pointer'}} onClick={() => toast('Profile menu opened')}>JM</button></div></header>
      <div className="sg-content"><div className="sg-welcome"><div><div className="sg-eyebrow">Tuesday · 14 May 2024</div><h1 className="sg-h1">Good morning, <em>Jordan.</em></h1></div><div className="sg-date"><b>One small check-in at a time.</b>Miso's daily care plan</div></div>
        <div className="sg-grid"><div style={{display:'flex',flexDirection:'column',gap:22}}><article className="sg-card sg-hero"><div className="sg-pet-select"><button className="sg-pet-button" onClick={() => setShowPetMenu(!showPetMenu)}><span className="sg-pet-photo" style={{background:pet.tone}}>{pet.initials}</span><span><span className="sg-pet-name">{pet.name} <ChevronDown size={15} style={{verticalAlign:'-2px'}}/></span><span className="sg-pet-meta">{pet.species} · <span style={{color:'#4e8e6d'}}>● {pet.status}</span></span></span></button><button className="sg-icon-button" style={{background:'#f6f1df',borderColor:'#e5ddc0'}} onClick={() => toast('Pet profile opened')}><MoreHorizontal size={18}/></button></div>{showPetMenu && <div className="sg-pet-menu">{petData.map((p,i)=><button key={p.name} onClick={() => {setActivePet(i);setShowPetMenu(false);toast(`${p.name}'s dashboard selected`)}}>{p.name} <span style={{color:'#9aa092'}}>· {p.species.split(' · ')[0]}</span></button>)}</div>}<div className="sg-health"><div><div className="sg-health-label">Weekly wellness</div><div className="sg-health-score">82 <small>/ 100</small></div><div style={{fontSize:11,color:'#788676',marginTop:4}}>Looking steady this week</div></div><div className="sg-ring"><span>82%</span></div></div><div className="sg-progress"><i/></div></article>
          <article className="sg-card"><div className="sg-card-head"><div><div className="sg-eyebrow" style={{marginBottom:5}}>Daily plan</div><div className="sg-card-title">{completed} of {tasks.length} check-ins complete</div></div><button className="sg-card-link" onClick={() => toast('Showing full health log')}>View log <ChevronRight size={12} style={{verticalAlign:'-2px'}}/></button></div><div className="sg-tasks">{tasks.map(task=><div className={`sg-task ${task.done?'is-done':''}`} key={task.id}><span className="sg-task-time">{task.time}</span><IconTile kind={task.kind}/><span><span className="sg-task-title">{task.title}</span><span className="sg-task-detail">{task.detail}</span></span><button className={`sg-check ${task.done?'checked':''}`} onClick={() => {toggleTask(task.id);toast(task.done?'Check-in reopened':'Check-in recorded')}} aria-label={`Mark ${task.title} ${task.done?'incomplete':'complete'}`}>{task.done&&<Check size={14}/>}</button></div>)}</div>{showComposer?<div className="sg-composer"><input autoFocus placeholder="e.g. Nail trim at 18:00" onKeyDown={e=>{if(e.key==='Enter'){setShowComposer(false);toast('Care note added')}}}/><button onClick={()=>{setShowComposer(false);toast('Care note added')}}>Add</button><button onClick={()=>setShowComposer(false)} style={{background:'#e9eee7',color:'#52705e',padding:10}}><X size={14}/></button></div>:<div style={{padding:'0 23px 19px'}}><button className="sg-add" onClick={()=>setShowComposer(true)}><Plus size={14} style={{verticalAlign:'-3px',marginRight:5}}/>Add a care note</button></div>}</article></div>
          <div className="sg-side-stack"><article className="sg-card sg-stat-card"><div className="sg-stat-row"><div><div className="sg-eyebrow" style={{marginBottom:8}}>Hydration · today</div><div className="sg-stat-main">620 <small>/ 800 ml</small></div><div className="sg-stat-note">78% of daily target</div></div><span className="sg-stat-icon"><Droplets size={18}/></span></div><div className="sg-mini-chart">{[34,48,28,62,48,72].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div style={{fontSize:10,color:'#929d96',display:'flex',justifyContent:'space-between',marginTop:7}}><span>6 am</span><span>now</span></div></article><article className="sg-card sg-next"><div className="sg-card-head" style={{padding:0}}><div><div className="sg-eyebrow" style={{marginBottom:5}}>Next appointment</div><div className="sg-card-title">Annual wellness exam</div></div><Stethoscope size={20} color="#668b72"/></div><div className="sg-next-box"><CalendarDays size={17} color="#668b72"/><div><strong>Thursday, 23 May</strong><span>10:30 · Cedar Grove Vet</span></div></div><button className="sg-add" onClick={()=>toast('Appointment details opened')}>View appointment <ChevronRight size={13} style={{verticalAlign:'-2px'}}/></button></article><article className="sg-card" style={{padding:'20px 22px',background:'#e5f0e8',borderColor:'#d2e2d6'}}><div style={{display:'flex',gap:11,alignItems:'flex-start'}}><ShieldCheck size={20} color="#4e8e6d"/><div><div style={{fontSize:13,fontWeight:700,color:'#37634b'}}>Everything looks on track</div><div style={{fontSize:11,color:'#6c8b78',lineHeight:1.5,marginTop:5}}>Miso's routine is 3 days stronger than last week.</div></div></div></article></div></div>
      </div></section>{notice&&<div className="sg-toast"><Sparkles size={13} style={{verticalAlign:'-2px',marginRight:7,color:'#d6b064'}}/>{notice}</div>}
  </main>;
}