import React, { useState } from 'react';
import {
  Bell, CalendarDays, Check, ChevronDown, ChevronRight, Clock3, HeartPulse,
  Home, Menu, PawPrint, Phone, Plus, Settings2, ShieldCheck, X,
} from 'lucide-react';

type EventItem = { id: number; time: string; title: string; detail: string; tag: string; done: boolean };
const pets = [
  { name: 'Miso', species: 'Shiba Inu · 4 yr', initials: 'MI', tone: '#b78a5c', status: 'Doing well' },
  { name: 'Basil', species: 'Tabby cat · 2 yr', initials: 'BA', tone: '#788e70', status: 'All caught up' },
];
const initialEvents: EventItem[] = [
  { id: 1, time: 'TODAY · 12:30', title: 'Midday water check', detail: 'Target 220 ml', tag: 'CARE', done: false },
  { id: 2, time: 'TODAY · 17:45', title: 'Evening walk', detail: '20–30 minutes · gentle pace', tag: 'ROUTINE', done: false },
  { id: 3, time: 'THU · 23 MAY', title: 'Annual wellness exam', detail: '10:30 · Cedar Grove Vet', tag: 'VISIT', done: false },
];
const vets = [
  { name: 'Cedar Grove Veterinary', role: 'Primary care · Miso + Basil', phone: '(415) 555-0184', initials: 'CG' },
  { name: 'Dr. Lena Ortiz', role: 'Dermatology · Miso', phone: '(415) 555-0127', initials: 'LO' },
];

export default function GuardianOperationsOriginalSections() {
  const [activePet, setActivePet] = useState(0);
  const [events, setEvents] = useState(initialEvents);
  const [tab, setTab] = useState('Home');
  const [composer, setComposer] = useState(false);
  const [notice, setNotice] = useState('');
  const pet = pets[activePet];
  const remaining = events.filter((event) => !event.done).length;
  const toast = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2200); };
  const toggleEvent = (id: number) => setEvents((current) => current.map((event) => event.id === id ? { ...event, done: !event.done } : event));

  return (
    <main className="go-shell">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Mono:wght@400;700&display=swap');
        .go-shell{min-height:100vh;background:#f1f3ee;color:#354239;font-family:'DM Sans',sans-serif;display:flex}
        .go-sidebar{width:214px;flex:0 0 214px;background:#35483f;color:#eef0e7;padding:23px 14px;display:flex;flex-direction:column}.go-brand{display:flex;align-items:center;gap:9px;padding:0 10px 31px;font-weight:700;letter-spacing:-.04em}.go-mark{width:29px;height:29px;border-radius:9px;background:#d5a83f;color:#35483f;display:grid;place-items:center}.go-label{font-size:9px;letter-spacing:.16em;text-transform:uppercase;color:#aeb9ad;margin:7px 11px 8px}.go-nav{display:flex;align-items:center;gap:10px;border:0;background:transparent;color:#bdc8bd;width:100%;padding:10px 11px;border-radius:9px;text-align:left;font:500 12px 'DM Sans';cursor:pointer}.go-nav:hover,.go-nav.active{background:#566b5d;color:#fff}.go-account{margin-top:auto;border-top:1px solid #58695d;padding:17px 8px 0;display:flex;gap:9px;align-items:center}.go-avatar{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:#718d76;color:#fff;font-size:10px;font-weight:700}
        .go-main{min-width:0;flex:1}.go-top{height:68px;background:#fbfcf8;border-bottom:1px solid #dce4da;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(18px,3.5vw,48px)}.go-mobile{display:none;border:0;background:none;color:#35483f}.go-context{font-size:12px;color:#8d978e}.go-context strong{color:#46584c}.go-actions{display:flex;gap:10px;align-items:center}.go-icon{width:35px;height:35px;border:1px solid #d6dfd5;background:#fbfcf8;border-radius:9px;color:#65766a;display:grid;place-items:center;cursor:pointer}
        .go-content{max-width:1180px;margin:auto;padding:31px clamp(18px,3.5vw,48px) 55px}.go-heading{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:22px}.go-kicker{color:#788b7c;font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.17em;margin-bottom:8px}.go-heading h1{margin:0;color:#304137;font-size:34px;letter-spacing:-.06em;line-height:1}.go-heading h1 em{color:#6e896f;font-style:normal}.go-date{font:10px/1.6 'Space Mono',monospace;color:#7b867d;text-align:right}.go-date b{color:#536657;display:block;font-size:11px}
        .go-petbar{display:flex;align-items:center;justify-content:space-between;background:#e6d7a8;border:1px solid #d6c484;border-radius:13px;padding:10px 14px;margin-bottom:18px}.go-pets{display:flex;gap:8px}.go-pet{display:flex;gap:8px;align-items:center;border:1px solid transparent;background:transparent;border-radius:9px;padding:6px 10px;color:#53604c;cursor:pointer;text-align:left;font:500 12px 'DM Sans'}.go-pet.selected{background:#f7f2df;border-color:#cdbd78;color:#35483f}.go-dot{width:27px;height:27px;border-radius:8px;color:#fff;display:grid;place-items:center;font-size:9px;font-weight:700}.go-pet small{display:block;color:#7c785f;font-size:9px;margin-top:2px}.go-scope{font-size:10px;color:#756d4b}.go-layout{display:grid;grid-template-columns:1fr;gap:18px}.go-stack{display:flex;flex-direction:column;gap:18px}.go-card{background:#fbfcf8;border:1px solid #dce4da;border-radius:14px;box-shadow:0 6px 18px rgba(48,70,57,.045)}.go-head{display:flex;align-items:flex-start;justify-content:space-between;padding:18px 20px 13px}.go-title{font-size:14px;font-weight:700;color:#3c4d42}.go-sub{font-size:10px;color:#8b968c;margin-top:3px}.go-link{border:0;background:none;color:#66816c;font:600 10px 'DM Sans';cursor:pointer}
        .go-pet-card{padding:19px 20px;background:#e5efe7;border-color:#d2e1d6}.go-pet-card-top{display:flex;justify-content:space-between;align-items:center}.go-pet-name{font-size:21px;letter-spacing:-.05em;font-weight:700;color:#304137}.go-pet-meta{font-size:11px;color:#708276;margin-top:4px}.go-health{display:flex;gap:24px;align-items:center;margin-top:18px}.go-health strong{font-size:29px;letter-spacing:-.06em}.go-health small{font-size:11px;color:#89958b;letter-spacing:0}.go-ring{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(#718d76 0 82%,#c6dac9 82%);position:relative;color:#52725a;font-size:12px;font-weight:700}.go-ring:after{content:'';position:absolute;inset:6px;border-radius:50%;background:#e5efe7}.go-ring span{position:relative;z-index:1}.go-rule{height:5px;border-radius:8px;background:#c7dac9;margin-top:15px;overflow:hidden}.go-rule i{display:block;width:82%;height:100%;background:#718d76}
        .go-list{padding:0 10px 10px}.go-row{display:grid;grid-template-columns:112px 1fr 26px;align-items:center;gap:12px;border-top:1px solid #e7ece5;padding:14px 10px}.go-time{font:10px 'Space Mono',monospace;color:#8e9990}.go-row strong{font-size:12px;color:#4a5b4f;display:block}.go-row span.detail{font-size:10px;color:#969f98;display:block;margin-top:3px}.go-tag{font:700 8px 'Space Mono',monospace;color:#aa7422;background:#f3e2c8;border-radius:5px;padding:5px 6px;justify-self:start}.go-tag.routine{color:#668d70;background:#e0ede3}.go-tag.visit{color:#6c7e91;background:#e2e9ee}.go-check{width:22px;height:22px;border-radius:7px;border:1px solid #ced9cf;background:#fbfcf8;color:transparent;display:grid;place-items:center;cursor:pointer}.go-check.checked{background:#718d76;border-color:#718d76;color:#fff}.go-row.is-done strong{text-decoration:line-through;color:#a3ada5}.go-add{border:1px dashed #bcae7b;background:#f8f4e8;color:#617b67;width:calc(100% - 20px);margin:0 10px 10px;padding:10px;border-radius:9px;font:600 11px 'DM Sans';cursor:pointer}.go-composer{display:flex;gap:6px;padding:12px 10px;border-top:1px solid #e6ebe4}.go-composer input{min-width:0;flex:1;border:1px solid #d4ddd4;border-radius:8px;padding:9px;font:11px 'DM Sans'}.go-composer button{border:0;border-radius:8px;background:#718d76;color:#fff;padding:9px 12px;font:600 11px 'DM Sans';cursor:pointer}
        .go-vets{padding-bottom:8px}.go-vet{display:grid;grid-template-columns:34px 1fr auto;gap:11px;align-items:center;border-top:1px solid #e7ece5;padding:13px 20px}.go-vet-mark{width:32px;height:32px;border-radius:9px;background:#f3e2c8;color:#a87323;display:grid;place-items:center;font-size:9px;font-weight:700}.go-vet strong{font-size:12px;display:block}.go-vet span{font-size:10px;color:#8d988f;display:block;margin-top:3px}.go-phone{border:0;background:#e6efe7;color:#66816c;border-radius:7px;width:28px;height:28px;display:grid;place-items:center;cursor:pointer}.go-toast{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#35483f;color:#fff;padding:10px 14px;border-radius:9px;font-size:11px;z-index:10}
        @media(max-width:820px){.go-sidebar{display:none}.go-mobile{display:block}.go-layout{grid-template-columns:1fr}.go-heading{align-items:flex-start;flex-direction:column;gap:10px}.go-date{text-align:left}.go-content{padding-top:25px}}@media(max-width:500px){.go-top{height:62px}.go-context{display:none}.go-heading h1{font-size:30px}.go-petbar{align-items:flex-start;flex-direction:column;gap:8px}.go-pets{width:100%}.go-pet{flex:1;padding-left:6px}.go-row{grid-template-columns:98px 1fr 22px;gap:7px;padding-left:4px;padding-right:4px}.go-vet{padding-left:12px;padding-right:12px}}
      `}</style>
      <aside className="go-sidebar">
        <div className="go-brand"><span className="go-mark"><PawPrint size={16} /></span>AgathaTrack</div>
        <div className="go-label">Guardian desk</div>
        {([['Home', Home], ['Pet health', HeartPulse], ['Appointments', CalendarDays], ['Pet profiles', PawPrint]] as const).map(([label, Icon]) => <button key={label} className={`go-nav ${tab === label ? 'active' : ''}`} onClick={() => { setTab(label); toast(`${label} selected`); }}><Icon size={16} />{label}</button>)}
        <div className="go-label" style={{ marginTop: 25 }}>Account</div><button className="go-nav" onClick={() => toast('Settings are ready to personalize')}><Settings2 size={16} />Settings</button>
        <div className="go-account"><div className="go-avatar">JM</div><div><div style={{ fontSize: 11, fontWeight: 600 }}>Jordan Miller</div><div style={{ fontSize: 9, color: '#aeb8ae', marginTop: 2 }}>Guardian account</div></div></div>
      </aside>
      <section className="go-main">
        <header className="go-top"><button className="go-mobile" onClick={() => toast('Navigation menu')} aria-label="Open navigation"><Menu size={20} /></button><div className="go-context">Workspace <ChevronRight size={12} style={{ verticalAlign: '-2px' }} /> <strong>{tab}</strong></div><div className="go-actions"><button className="go-icon" onClick={() => toast('No new notifications')} aria-label="Notifications"><Bell size={16} /></button><button className="go-avatar" style={{ border: 0, cursor: 'pointer' }} onClick={() => toast('Profile menu opened')} aria-label="Open profile">JM</button></div></header>
        <div className="go-content">
          <div className="go-heading"><div><div className="go-kicker">Tuesday · 14 May 2024 / guardian view</div><h1>Good morning, <em>Jordan.</em></h1></div><div className="go-date"><b>{remaining} items to review</b>{pet.name}'s care plan · last synced 09:42</div></div>
          <div className="go-layout">
            <div className="go-stack">
              <article className="go-card go-pet-card"><div className="go-head" style={{ padding: '0 0 14px' }}><div><div className="go-kicker" style={{ marginBottom: 5 }}>Guardian profiles</div><div className="go-title">My Pets</div><div className="go-sub">Choose a pet to review their care details.</div></div><button className="go-link" onClick={() => toast('Pet manager opened')}>Manage pets <ChevronRight size={11} style={{ verticalAlign: '-2px' }} /></button></div><div className="go-petbar" style={{ marginBottom: 0 }}><div className="go-pets">{pets.map((p, i) => <button key={p.name} className={`go-pet ${activePet === i ? 'selected' : ''}`} onClick={() => { setActivePet(i); toast(`${p.name}'s profile selected`); }}><span className="go-dot" style={{ background: p.tone }}>{p.initials}</span><span><b>{p.name}</b><small>{p.status}</small></span></button>)}</div><div className="go-scope"><ShieldCheck size={13} style={{ verticalAlign: '-3px', marginRight: 4 }} />Personal care · {pet.name}<ChevronDown size={12} style={{ verticalAlign: '-2px', marginLeft: 5 }} /></div></div><div className="go-pet-card-top" style={{ marginTop: 18 }}><div><div className="go-pet-meta">Current profile</div><div className="go-pet-name">{pet.name}</div><div className="go-pet-meta">{pet.species} · <span style={{ color: '#668d70' }}>● {pet.status}</span></div></div><button className="go-icon" onClick={() => toast('Pet actions opened')} aria-label={`Open ${pet.name} actions`}><ChevronDown size={16} /></button></div><div className="go-health"><div><div className="go-kicker" style={{ marginBottom: 5 }}>Wellness signal</div><strong>82 <small>/ 100</small></strong><div className="go-sub">Steady this week</div></div><div className="go-ring"><span>82%</span></div></div><div className="go-rule"><i /></div></article>
              <article className="go-card"><div className="go-head"><div><div className="go-kicker" style={{ marginBottom: 5 }}>Guardian schedule</div><div className="go-title">Upcoming Pet Events</div><div className="go-sub">{remaining} next actions · ordered by time</div></div><button className="go-link" onClick={() => toast('Full calendar opened')}>View calendar <ChevronRight size={11} style={{ verticalAlign: '-2px' }} /></button></div><div className="go-list">{events.map((event) => <div className={`go-row ${event.done ? 'is-done' : ''}`} key={event.id}><span className={`go-tag ${event.tag.toLowerCase()}`}>{event.tag}</span><span><span className="go-time">{event.time}</span><strong>{event.title}</strong><span className="detail">{event.detail}</span></span><button className={`go-check ${event.done ? 'checked' : ''}`} onClick={() => { toggleEvent(event.id); toast(event.done ? 'Event reopened' : 'Event marked complete'); }} aria-label={`${event.done ? 'Reopen' : 'Complete'} ${event.title}`}>{event.done && <Check size={13} />}</button></div>)}</div>{composer ? <div className="go-composer"><input autoFocus placeholder="e.g. Nail trim at 18:00" onKeyDown={(e) => { if (e.key === 'Enter') { setComposer(false); toast('Pet event added'); } }} /><button onClick={() => { setComposer(false); toast('Pet event added'); }}>Add</button><button onClick={() => setComposer(false)} style={{ background: '#e8ece6', color: '#627b68' }} aria-label="Cancel"><X size={13} /></button></div> : <button className="go-add" onClick={() => setComposer(true)}><Plus size={13} style={{ verticalAlign: '-3px', marginRight: 4 }} /> Add a pet event</button>}</article>
              <article className="go-card go-vets"><div className="go-head"><div><div className="go-kicker" style={{ marginBottom: 5 }}>Care network</div><div className="go-title">My Vets</div><div className="go-sub">Trusted contacts for {pet.name}</div></div><button className="go-link" onClick={() => toast('Vet directory opened')}>Manage <ChevronRight size={11} style={{ verticalAlign: '-2px' }} /></button></div>{vets.map((vet) => <div className="go-vet" key={vet.name}><div className="go-vet-mark">{vet.initials}</div><div><strong>{vet.name}</strong><span>{vet.role} · {vet.phone}</span></div><button className="go-phone" onClick={() => toast(`Calling ${vet.name}`)} aria-label={`Call ${vet.name}`}><Phone size={13} /></button></div>)}</article>
            </div>
          </div>
        </div>
      </section>
      {notice && <div className="go-toast"><Clock3 size={12} style={{ verticalAlign: '-2px', marginRight: 6, color: '#d5a83f' }} />{notice}</div>}
    </main>
  );
}