import React, { useState } from 'react';
import {
  Activity, Bell, CalendarDays, Check, ChevronDown, ChevronRight, Droplets,
  HeartPulse, Home, Menu, MoreHorizontal, PawPrint, Pill, Plus, Settings2,
  ShieldCheck, Sparkles, Stethoscope, X,
} from 'lucide-react';

type Task = { id: number; time: string; title: string; detail: string; kind: 'medicine' | 'care' | 'walk'; done: boolean };
const initialTasks: Task[] = [
  { id: 1, time: '08:00', title: 'Breakfast + probiotic', detail: '1 scoop · with food', kind: 'medicine', done: true },
  { id: 2, time: '12:30', title: 'Midday water check', detail: 'Target 220 ml', kind: 'care', done: false },
  { id: 3, time: '17:45', title: 'Evening walk', detail: '20–30 minutes · gentle pace', kind: 'walk', done: false },
  { id: 4, time: '21:00', title: 'Joint supplement', detail: '1 chew · after dinner', kind: 'medicine', done: false },
];
const petData = [
  { name: 'Miso', species: 'Shiba Inu · 4 yr', initials: 'MI', tone: '#c58aa7', status: 'Doing well' },
  { name: 'Basil', species: 'Tabby cat · 2 yr', initials: 'BA', tone: '#799e9a', status: 'All caught up' },
];

function IconTile({ kind }: { kind: Task['kind'] }) {
  const Icon = kind === 'medicine' ? Pill : kind === 'walk' ? Activity : Droplets;
  return <span className={`mo-icon mo-${kind}`}><Icon size={17} strokeWidth={1.8} /></span>;
}

export default function GuardianCockpitMidnightOrchid() {
  const [activePet, setActivePet] = useState(0);
  const [tasks, setTasks] = useState(initialTasks);
  const [tab, setTab] = useState('Today');
  const [showPetMenu, setShowPetMenu] = useState(false);
  const [showComposer, setShowComposer] = useState(false);
  const [notice, setNotice] = useState('');
  const pet = petData[activePet];
  const completed = tasks.filter((task) => task.done).length;
  const toast = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2400); };
  const toggleTask = (id: number) => setTasks((current) => current.map((task) => task.id === id ? { ...task, done: !task.done } : task));

  return <main className="mo-shell">
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500&display=swap');
      .mo-shell{min-height:100vh;background:#f5f0f7;color:#30283a;font-family:'DM Sans',sans-serif;display:flex}
      .mo-sidebar{width:226px;flex:0 0 226px;background:#241c32;color:#f7f1f8;padding:25px 16px 20px;display:flex;flex-direction:column}
      .mo-brand{display:flex;align-items:center;gap:10px;padding:0 10px 32px;font-weight:700;letter-spacing:-.03em}.mo-brand-mark{width:30px;height:30px;border-radius:10px;background:#d99bc4;display:grid;place-items:center;color:#241c32}
      .mo-nav-label{color:#a99bb2;font-size:10px;letter-spacing:.14em;text-transform:uppercase;margin:8px 12px 10px}.mo-nav{display:flex;align-items:center;gap:11px;width:100%;border:0;background:none;color:#b9aebe;padding:11px 12px;border-radius:11px;text-align:left;font:500 13px 'DM Sans';cursor:pointer}.mo-nav.active{color:#fff;background:#4d385a}.mo-nav:hover{background:#392a46;color:#fff}.mo-sidebar-foot{margin-top:auto;border-top:1px solid #45364f;padding-top:18px}
      .mo-main{min-width:0;flex:1}.mo-topbar{height:78px;background:#fbf9fc;border-bottom:1px solid #e5dce9;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(20px,4vw,56px)}.mo-menu{display:none;border:0;background:none;color:#241c32}.mo-crumb{font-size:12px;color:#8e8295;display:flex;gap:8px;align-items:center}.mo-crumb strong{color:#493c50}.mo-top-actions{display:flex;gap:12px;align-items:center}.mo-icon-button{width:38px;height:38px;border:1px solid #dfd3e5;background:#fff;border-radius:11px;display:grid;place-items:center;color:#746681;cursor:pointer}.mo-avatar{width:37px;height:37px;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:11px;font-weight:700}
      .mo-content{max-width:1120px;margin:0 auto;padding:43px clamp(20px,4vw,56px) 60px}.mo-welcome{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:32px}.mo-eyebrow{color:#8b6b9e;text-transform:uppercase;letter-spacing:.15em;font-size:10px;font-weight:700;margin-bottom:10px}.mo-h1{font-size:clamp(28px,4vw,40px);line-height:1.05;letter-spacing:-.055em;margin:0;color:#30243a}.mo-h1 em{font-family:Fraunces,serif;font-weight:500;color:#7c4d83;font-style:normal}.mo-date{color:#817687;font-size:13px;text-align:right;line-height:1.5}.mo-date b{color:#493750;display:block;font-size:14px}
      .mo-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(260px,.8fr);gap:22px}.mo-card{background:#fffdfd;border:1px solid #e5dbe9;border-radius:18px;box-shadow:0 8px 24px rgba(54,30,64,.06)}.mo-hero{padding:24px;background:#e8dced;border-color:#d9c6e2;position:relative;overflow:hidden}.mo-hero:after{content:'';position:absolute;right:-55px;top:-75px;width:220px;height:220px;border-radius:50%;border:1px solid rgba(124,77,131,.22);box-shadow:0 0 0 22px rgba(124,77,131,.06),0 0 0 44px rgba(124,77,131,.04)}
      .mo-pet-select{position:relative;z-index:2;display:flex;align-items:center;justify-content:space-between}.mo-pet-button{display:flex;align-items:center;gap:12px;background:none;border:0;padding:0;cursor:pointer;color:#34253d;text-align:left}.mo-pet-photo{width:54px;height:54px;border-radius:17px;display:grid;place-items:center;color:#fff;font-weight:700;letter-spacing:.06em;box-shadow:inset 0 0 0 4px rgba(255,255,255,.3)}.mo-pet-name{font-weight:700;font-size:20px;letter-spacing:-.04em;display:block}.mo-pet-meta{color:#755d7c;font-size:12px;display:block;margin-top:2px}.mo-pet-menu{position:absolute;right:24px;top:84px;background:#fffdfd;border:1px solid #dfd1e5;border-radius:12px;padding:5px;box-shadow:0 12px 30px #3623441a;z-index:5;min-width:150px}.mo-pet-menu button{width:100%;border:0;background:none;padding:9px;text-align:left;border-radius:8px;color:#55445e;cursor:pointer;font:500 12px 'DM Sans'}.mo-pet-menu button:hover{background:#f0e7f3}
      .mo-health{margin-top:27px;display:flex;align-items:flex-end;justify-content:space-between;position:relative;z-index:1}.mo-health-label{color:#755d7c;font-size:12px;margin-bottom:7px}.mo-health-score{font-size:37px;letter-spacing:-.06em;font-weight:700;color:#392b45}.mo-health-score small{font-size:14px;color:#8e7897;font-weight:500;letter-spacing:0}.mo-ring{width:91px;height:91px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(#7c4d83 0 82%,#d2bddb 82% 100%);position:relative}.mo-ring:after{content:'';position:absolute;inset:8px;background:#e8dced;border-radius:50%}.mo-ring span{position:relative;z-index:1;font-size:18px;font-weight:700;color:#62406c}.mo-progress{height:5px;background:#d2bddb;border-radius:9px;margin-top:17px;overflow:hidden;position:relative;z-index:1}.mo-progress i{display:block;width:82%;height:100%;background:#7c4d83;border-radius:9px}
      .mo-card-head{display:flex;align-items:center;justify-content:space-between;padding:21px 23px 14px}.mo-card-title{font-size:15px;font-weight:700;letter-spacing:-.02em}.mo-card-link{color:#7c4d83;border:0;background:none;font:600 11px 'DM Sans';cursor:pointer}.mo-tasks{padding:0 12px 10px}.mo-task{display:grid;grid-template-columns:50px 35px 1fr 28px;align-items:center;gap:10px;padding:13px 11px;border-top:1px solid #eee8f1}.mo-task-time{font-size:11px;color:#94889b;font-variant-numeric:tabular-nums}.mo-icon{width:33px;height:33px;border-radius:10px;display:grid;place-items:center}.mo-medicine{background:#f2e0eb;color:#ad608c}.mo-care{background:#deefec;color:#3c817c}.mo-walk{background:#e3e3f4;color:#6463a0}.mo-task-title{font-size:13px;font-weight:600;color:#43334b;display:block}.mo-task-detail{font-size:11px;color:#968b9a;margin-top:3px;display:block}.mo-task.is-done .mo-task-title{text-decoration:line-through;color:#aaa0ae}.mo-check{width:23px;height:23px;border:1px solid #d8cbdc;border-radius:50%;background:#fff;display:grid;place-items:center;color:transparent;cursor:pointer}.mo-check.checked{background:#3c817c;border-color:#3c817c;color:#fff}
      .mo-stat-card{padding:22px 23px}.mo-stat-row{display:flex;justify-content:space-between;align-items:center}.mo-stat-main{font-size:30px;font-weight:700;letter-spacing:-.05em;color:#392b45}.mo-stat-main small{font-size:12px;font-weight:500;color:#978a9d;letter-spacing:0}.mo-stat-note{font-size:11px;color:#8f8395;margin-top:5px}.mo-stat-icon{width:37px;height:37px;border-radius:12px;background:#deefec;color:#3c817c;display:grid;place-items:center}.mo-mini-chart{display:flex;align-items:flex-end;gap:7px;height:53px;margin-top:22px}.mo-mini-chart i{flex:1;background:#c6dfdc;border-radius:5px 5px 2px 2px;min-height:15px}.mo-mini-chart i:nth-child(4),.mo-mini-chart i:last-child{background:#3c817c}.mo-side-stack{display:flex;flex-direction:column;gap:22px}.mo-next{padding:22px 23px}.mo-next-box{background:#f0e9f4;border-radius:12px;padding:14px;margin-top:14px;display:flex;gap:11px;align-items:center}.mo-next-box strong{font-size:12px;display:block}.mo-next-box span{font-size:11px;color:#91849a;display:block;margin-top:3px}.mo-add{width:100%;border:1px dashed #c8b5d0;border-radius:11px;background:#faf6fb;color:#7c4d83;font:600 12px 'DM Sans';padding:12px;cursor:pointer;margin-top:12px}.mo-composer{border-top:1px solid #ebe2f0;padding:14px 12px;display:flex;gap:8px;align-items:center}.mo-composer input{flex:1;border:1px solid #ded1e3;border-radius:9px;padding:10px;font:12px 'DM Sans';outline:none}.mo-composer button{border:0;border-radius:9px;background:#7c4d83;color:#fff;padding:10px 14px;font:600 12px 'DM Sans';cursor:pointer}.mo-toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:#241c32;color:#fff;padding:11px 15px;border-radius:10px;font-size:12px;box-shadow:0 8px 22px #241c3233;z-index:20}
      @media(max-width:800px){.mo-sidebar{display:none}.mo-menu{display:block}.mo-grid{grid-template-columns:1fr}.mo-welcome{align-items:flex-start;flex-direction:column}.mo-date{text-align:left}.mo-content{padding-top:28px}}@media(max-width:480px){.mo-topbar{height:65px}.mo-crumb{display:none}.mo-task{grid-template-columns:43px 32px 1fr 25px;gap:7px;padding-left:4px;padding-right:4px}.mo-hero{padding:19px}}
    `}</style>
    <aside className="mo-sidebar"><div className="mo-brand"><span className="mo-brand-mark"><PawPrint size={17}/></span><span>AgathaTrack</span></div><div className="mo-nav-label">Workspace</div>
      {([['Today',Home],['Health log',HeartPulse],['Appointments',CalendarDays],['Pet profiles',PawPrint]] as const).map(([label,NavIcon])=><button key={label} className={`mo-nav ${tab===label?'active':''}`} onClick={()=>{setTab(label);toast(`${label} view selected`)}}><NavIcon size={17} strokeWidth={1.8}/>{label}</button>)}
      <div className="mo-nav-label" style={{marginTop:27}}>Account</div><button className="mo-nav" onClick={()=>toast('Settings are ready to personalize')}><Settings2 size={17} strokeWidth={1.8}/>Settings</button>
      <div className="mo-sidebar-foot"><div style={{display:'flex',alignItems:'center',gap:10,padding:'0 9px'}}><div className="mo-avatar" style={{background:'#76507e'}}>JM</div><div><div style={{fontSize:12,fontWeight:600}}>Jordan Miller</div><div style={{fontSize:10,color:'#a99bb2',marginTop:2}}>Guardian account</div></div></div></div>
    </aside>
    <section className="mo-main"><header className="mo-topbar"><button className="mo-menu" onClick={()=>toast('Navigation menu')}><Menu size={21}/></button><div className="mo-crumb"><span>Workspace</span><ChevronRight size={13}/><strong>{tab}</strong></div><div className="mo-top-actions"><button className="mo-icon-button" onClick={()=>toast('No new notifications')}><Bell size={17}/></button><button className="mo-avatar" style={{background:'#76507e',border:0,cursor:'pointer'}} onClick={()=>toast('Profile menu opened')}>JM</button></div></header>
      <div className="mo-content"><div className="mo-welcome"><div><div className="mo-eyebrow">Tuesday · 14 May 2024</div><h1 className="mo-h1">Good morning, <em>Jordan.</em></h1></div><div className="mo-date"><b>One small check-in at a time.</b>Miso's daily care plan</div></div>
        <div className="mo-grid"><div style={{display:'flex',flexDirection:'column',gap:22}}><article className="mo-card mo-hero"><div className="mo-pet-select"><button className="mo-pet-button" onClick={()=>setShowPetMenu(!showPetMenu)}><span className="mo-pet-photo" style={{background:pet.tone}}>{pet.initials}</span><span><span className="mo-pet-name">{pet.name} <ChevronDown size={15} style={{verticalAlign:'-2px'}}/></span><span className="mo-pet-meta">{pet.species} · <span style={{color:'#3c817c'}}>● {pet.status}</span></span></span></button><button className="mo-icon-button" style={{background:'#f4e9f5',borderColor:'#dfcbe5'}} onClick={()=>toast('Pet profile opened')}><MoreHorizontal size={18}/></button></div>
          {showPetMenu&&<div className="mo-pet-menu">{petData.map((p,i)=><button key={p.name} onClick={()=>{setActivePet(i);setShowPetMenu(false);toast(`${p.name}'s dashboard selected`)}}>{p.name} <span style={{color:'#a296a8'}}>· {p.species.split(' · ')[0]}</span></button>)}</div>}<div className="mo-health"><div><div className="mo-health-label">Weekly wellness</div><div className="mo-health-score">82 <small>/ 100</small></div><div style={{fontSize:11,color:'#806b87',marginTop:4}}>Looking steady this week</div></div><div className="mo-ring"><span>82%</span></div></div><div className="mo-progress"><i/></div></article>
          <article className="mo-card"><div className="mo-card-head"><div><div className="mo-eyebrow" style={{marginBottom:5}}>Daily plan</div><div className="mo-card-title">{completed} of {tasks.length} check-ins complete</div></div><button className="mo-card-link" onClick={()=>toast('Showing full health log')}>View log <ChevronRight size={12} style={{verticalAlign:'-2px'}}/></button></div><div className="mo-tasks">{tasks.map(task=><div className={`mo-task ${task.done?'is-done':''}`} key={task.id}><span className="mo-task-time">{task.time}</span><IconTile kind={task.kind}/><span><span className="mo-task-title">{task.title}</span><span className="mo-task-detail">{task.detail}</span></span><button className={`mo-check ${task.done?'checked':''}`} onClick={()=>{toggleTask(task.id);toast(task.done?'Check-in reopened':'Check-in recorded')}} aria-label={`Mark ${task.title} ${task.done?'incomplete':'complete'}`}>{task.done&&<Check size={14}/>}</button></div>)}</div>{showComposer?<div className="mo-composer"><input autoFocus placeholder="e.g. Nail trim at 18:00" onKeyDown={e=>{if(e.key==='Enter'){setShowComposer(false);toast('Care note added')}}}/><button onClick={()=>{setShowComposer(false);toast('Care note added')}}>Add</button><button onClick={()=>setShowComposer(false)} style={{background:'#eee6f1',color:'#725d7c',padding:10}}><X size={14}/></button></div>:<div style={{padding:'0 23px 19px'}}><button className="mo-add" onClick={()=>setShowComposer(true)}><Plus size={14} style={{verticalAlign:'-3px',marginRight:5}}/>Add a care note</button></div>}</article></div>
          <div className="mo-side-stack"><article className="mo-card mo-stat-card"><div className="mo-stat-row"><div><div className="mo-eyebrow" style={{marginBottom:8}}>Hydration · today</div><div className="mo-stat-main">620 <small>/ 800 ml</small></div><div className="mo-stat-note">78% of daily target</div></div><span className="mo-stat-icon"><Droplets size={18}/></span></div><div className="mo-mini-chart">{[34,48,28,62,48,72].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div style={{fontSize:10,color:'#9b8e9e',display:'flex',justifyContent:'space-between',marginTop:7}}><span>6 am</span><span>now</span></div></article>
            <article className="mo-card mo-next"><div className="mo-card-head" style={{padding:0}}><div><div className="mo-eyebrow" style={{marginBottom:5}}>Next appointment</div><div className="mo-card-title">Annual wellness exam</div></div><Stethoscope size={20} color="#7c4d83"/></div><div className="mo-next-box"><CalendarDays size={17} color="#7c4d83"/><div><strong>Thursday, 23 May</strong><span>10:30 · Cedar Grove Vet</span></div></div><button className="mo-add" onClick={()=>toast('Appointment details opened')}>View appointment <ChevronRight size={13} style={{verticalAlign:'-2px'}}/></button></article>
            <article className="mo-card" style={{padding:'20px 22px',background:'#e5f1ef',borderColor:'#d0e4e0'}}><div style={{display:'flex',gap:11,alignItems:'flex-start'}}><ShieldCheck size={20} color="#3c817c"/><div><div style={{fontSize:13,fontWeight:700,color:'#315c59'}}>Everything looks on track</div><div style={{fontSize:11,color:'#668581',lineHeight:1.5,marginTop:5}}>Miso's routine is 3 days stronger than last week.</div></div></div></article>
          </div></div></div></section>{notice&&<div className="mo-toast"><Sparkles size={13} style={{verticalAlign:'-2px',marginRight:7,color:'#d99bc4'}}/>{notice}</div>}
  </main>;
}