import React, { useState } from 'react';
import {
  Activity, Bell, CalendarDays, Check, ChevronDown, ChevronRight, Droplets,
  HeartPulse, Home, Menu, MoreHorizontal, PawPrint, Pill, Plus, Settings2,
  ShieldCheck, Sparkles, Stethoscope, X,
} from 'lucide-react';

type Task = { id: number; time: string; title: string; detail: string; kind: 'medicine' | 'care' | 'walk'; done: boolean };
const initialTasks: Task[] = [
  { id: 1, time: '08:00', title: 'Breakfast + probiotic', detail: '1 scoop · with food', kind: 'medicine', done: true },
  { id: 2, time: '12:30', title: 'Midday water check', detail: 'Target 220 ml', kind: 'care', done: false },
  { id: 3, time: '17:45', title: 'Evening walk', detail: '20–30 minutes · gentle pace', kind: 'walk', done: false },
  { id: 4, time: '21:00', title: 'Joint supplement', detail: '1 chew · after dinner', kind: 'medicine', done: false },
];
const petData = [
  { name: 'Miso', species: 'Shiba Inu · 4 yr', initials: 'MI', tone: '#d59b58', status: 'Doing well' },
  { name: 'Basil', species: 'Tabby cat · 2 yr', initials: 'BA', tone: '#70a9a0', status: 'All caught up' },
];

function IconTile({ kind }: { kind: Task['kind'] }) {
  const Icon = kind === 'medicine' ? Pill : kind === 'walk' ? Activity : Droplets;
  return <span className={`lm-icon lm-${kind}`}><Icon size={17} strokeWidth={1.8} /></span>;
}

export default function GuardianShelterLagoonMarigold() {
  const [activePet, setActivePet] = useState(0);
  const [tasks, setTasks] = useState(initialTasks);
  const [tab, setTab] = useState('Today');
  const [showPetMenu, setShowPetMenu] = useState(false);
  const [showComposer, setShowComposer] = useState(false);
  const [notice, setNotice] = useState('');
  const pet = petData[activePet];
  const completed = tasks.filter((task) => task.done).length;
  const toast = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2400); };
  const toggleTask = (id: number) => setTasks((current) => current.map((task) => task.id === id ? { ...task, done: !task.done } : task));

  return <main className="lm-shell">
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500&display=swap');
      .lm-shell{min-height:100vh;background:#f2f7f5;color:#273c3b;font-family:'DM Sans',sans-serif;display:flex}
      .lm-sidebar{width:226px;flex:0 0 226px;background:#203c3b;color:#eef7f3;padding:25px 16px 20px;display:flex;flex-direction:column}
      .lm-brand{display:flex;align-items:center;gap:10px;padding:0 10px 32px;font-weight:700;letter-spacing:-.03em}.lm-brand-mark{width:30px;height:30px;border-radius:10px;background:#e0aa3f;display:grid;place-items:center;color:#203c3b}
      .lm-nav-label{color:#91b0aa;font-size:10px;letter-spacing:.14em;text-transform:uppercase;margin:8px 12px 10px}.lm-nav{display:flex;align-items:center;gap:11px;width:100%;border:0;background:none;color:#a9c4bf;padding:11px 12px;border-radius:11px;text-align:left;font:500 13px 'DM Sans';cursor:pointer}.lm-nav.active{color:#fff;background:#35615d}.lm-nav:hover{background:#2c514e;color:#fff}.lm-sidebar-foot{margin-top:auto;border-top:1px solid #385a56;padding-top:18px}
      .lm-main{min-width:0;flex:1}.lm-topbar{height:78px;background:#fbfdfb;border-bottom:1px solid #dce9e4;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(20px,4vw,56px)}.lm-menu{display:none;border:0;background:none;color:#203c3b}.lm-crumb{font-size:12px;color:#78908b;display:flex;gap:8px;align-items:center}.lm-crumb strong{color:#36534f}.lm-top-actions{display:flex;gap:12px;align-items:center}.lm-icon-button{width:38px;height:38px;border:1px solid #d7e5df;background:#fff;border-radius:11px;display:grid;place-items:center;color:#597671;cursor:pointer}.lm-avatar{width:37px;height:37px;border-radius:50%;display:grid;place-items:center;color:#fff;font-size:11px;font-weight:700}
      .lm-content{max-width:1120px;margin:0 auto;padding:43px clamp(20px,4vw,56px) 60px}.lm-welcome{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:32px}.lm-eyebrow{color:#bf8624;text-transform:uppercase;letter-spacing:.15em;font-size:10px;font-weight:700;margin-bottom:10px}.lm-h1{font-size:clamp(28px,4vw,40px);line-height:1.05;letter-spacing:-.055em;margin:0;color:#29403d}.lm-h1 em{font-family:Fraunces,serif;font-weight:500;color:#268c87;font-style:normal}.lm-date{color:#718984;font-size:13px;text-align:right;line-height:1.5}.lm-date b{color:#395b56;display:block;font-size:14px}
      .lm-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(260px,.8fr);gap:22px}.lm-card{background:#fffefd;border:1px solid #dce9e4;border-radius:18px;box-shadow:0 8px 24px rgba(34,79,72,.07)}.lm-hero{padding:24px;background:#dff0ec;border-color:#c5e1db;position:relative;overflow:hidden}.lm-hero:after{content:'';position:absolute;right:-55px;top:-75px;width:220px;height:220px;border-radius:50%;border:1px solid rgba(38,140,135,.24);box-shadow:0 0 0 22px rgba(38,140,135,.07),0 0 0 44px rgba(38,140,135,.04)}
      .lm-pet-select{position:relative;z-index:2;display:flex;align-items:center;justify-content:space-between}.lm-pet-button{display:flex;align-items:center;gap:12px;background:none;border:0;padding:0;cursor:pointer;color:#29413e;text-align:left}.lm-pet-photo{width:54px;height:54px;border-radius:17px;display:grid;place-items:center;color:#fff;font-weight:700;letter-spacing:.06em;box-shadow:inset 0 0 0 4px rgba(255,255,255,.3)}.lm-pet-name{font-weight:700;font-size:20px;letter-spacing:-.04em;display:block}.lm-pet-meta{color:#587771;font-size:12px;display:block;margin-top:2px}.lm-pet-menu{position:absolute;right:24px;top:84px;background:#fffefd;border:1px solid #d4e4de;border-radius:12px;padding:5px;box-shadow:0 12px 30px #244c4520;z-index:5;min-width:150px}.lm-pet-menu button{width:100%;border:0;background:none;padding:9px;text-align:left;border-radius:8px;color:#47625e;cursor:pointer;font:500 12px 'DM Sans'}.lm-pet-menu button:hover{background:#edf5f1}
      .lm-health{margin-top:27px;display:flex;align-items:flex-end;justify-content:space-between;position:relative;z-index:1}.lm-health-label{color:#587771;font-size:12px;margin-bottom:7px}.lm-health-score{font-size:37px;letter-spacing:-.06em;font-weight:700;color:#29413e}.lm-health-score small{font-size:14px;color:#78948e;font-weight:500;letter-spacing:0}.lm-ring{width:91px;height:91px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(#268c87 0 82%,#b9dcd5 82% 100%);position:relative}.lm-ring:after{content:'';position:absolute;inset:8px;background:#dff0ec;border-radius:50%}.lm-ring span{position:relative;z-index:1;font-size:18px;font-weight:700;color:#277772}.lm-progress{height:5px;background:#b9dcd5;border-radius:9px;margin-top:17px;overflow:hidden;position:relative;z-index:1}.lm-progress i{display:block;width:82%;height:100%;background:#268c87;border-radius:9px}
      .lm-card-head{display:flex;align-items:center;justify-content:space-between;padding:21px 23px 14px}.lm-card-title{font-size:15px;font-weight:700;letter-spacing:-.02em}.lm-card-link{color:#268c87;border:0;background:none;font:600 11px 'DM Sans';cursor:pointer}.lm-tasks{padding:0 12px 10px}.lm-task{display:grid;grid-template-columns:50px 35px 1fr 28px;align-items:center;gap:10px;padding:13px 11px;border-top:1px solid #e7efec}.lm-task-time{font-size:11px;color:#829793;font-variant-numeric:tabular-nums}.lm-icon{width:33px;height:33px;border-radius:10px;display:grid;place-items:center}.lm-medicine{background:#faead2;color:#bb7c1b}.lm-care{background:#dcefeb;color:#338681}.lm-walk{background:#e6f0dc;color:#698b43}.lm-task-title{font-size:13px;font-weight:600;color:#3d5753;display:block}.lm-task-detail{font-size:11px;color:#889a96;margin-top:3px;display:block}.lm-task.is-done .lm-task-title{text-decoration:line-through;color:#a5b1ae}.lm-check{width:23px;height:23px;border:1px solid #d1e0da;border-radius:50%;background:#fff;display:grid;place-items:center;color:transparent;cursor:pointer}.lm-check.checked{background:#268c87;border-color:#268c87;color:#fff}
      .lm-stat-card{padding:22px 23px}.lm-stat-row{display:flex;justify-content:space-between;align-items:center}.lm-stat-main{font-size:30px;font-weight:700;letter-spacing:-.05em;color:#29413e}.lm-stat-main small{font-size:12px;font-weight:500;color:#899d99;letter-spacing:0}.lm-stat-note{font-size:11px;color:#829793;margin-top:5px}.lm-stat-icon{width:37px;height:37px;border-radius:12px;background:#dcefeb;color:#338681;display:grid;place-items:center}.lm-mini-chart{display:flex;align-items:flex-end;gap:7px;height:53px;margin-top:22px}.lm-mini-chart i{flex:1;background:#b8dbd4;border-radius:5px 5px 2px 2px;min-height:15px}.lm-mini-chart i:nth-child(4),.lm-mini-chart i:last-child{background:#338681}.lm-side-stack{display:flex;flex-direction:column;gap:22px}.lm-next{padding:22px 23px}.lm-next-box{background:#f8edd9;border-radius:12px;padding:14px;margin-top:14px;display:flex;gap:11px;align-items:center}.lm-next-box strong{font-size:12px;display:block}.lm-next-box span{font-size:11px;color:#8b9389;display:block;margin-top:3px}.lm-add{width:100%;border:1px dashed #b6cbc4;border-radius:11px;background:#f8fbf9;color:#268c87;font:600 12px 'DM Sans';padding:12px;cursor:pointer;margin-top:12px}.lm-composer{border-top:1px solid #e4eeea;padding:14px 12px;display:flex;gap:8px;align-items:center}.lm-composer input{flex:1;border:1px solid #d3e2dc;border-radius:9px;padding:10px;font:12px 'DM Sans';outline:none}.lm-composer button{border:0;border-radius:9px;background:#268c87;color:#fff;padding:10px 14px;font:600 12px 'DM Sans';cursor:pointer}.lm-toast{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);background:#203c3b;color:#fff;padding:11px 15px;border-radius:10px;font-size:12px;box-shadow:0 8px 22px #203c3b33;z-index:20}
      @media(max-width:800px){.lm-sidebar{display:none}.lm-menu{display:block}.lm-grid{grid-template-columns:1fr}.lm-welcome{align-items:flex-start;flex-direction:column}.lm-date{text-align:left}.lm-content{padding-top:28px}}@media(max-width:480px){.lm-topbar{height:65px}.lm-crumb{display:none}.lm-task{grid-template-columns:43px 32px 1fr 25px;gap:7px;padding-left:4px;padding-right:4px}.lm-hero{padding:19px}}
    `}</style>
    <aside className="lm-sidebar"><div className="lm-brand"><span className="lm-brand-mark"><PawPrint size={17}/></span><span>AgathaTrack</span></div><div className="lm-nav-label">Workspace</div>
      {([['Today',Home],['Health log',HeartPulse],['Appointments',CalendarDays],['Pet profiles',PawPrint]] as const).map(([label,NavIcon])=><button key={label} className={`lm-nav ${tab===label?'active':''}`} onClick={()=>{setTab(label);toast(`${label} view selected`)}}><NavIcon size={17} strokeWidth={1.8}/>{label}</button>)}
      <div className="lm-nav-label" style={{marginTop:27}}>Account</div><button className="lm-nav" onClick={()=>toast('Settings are ready to personalize')}><Settings2 size={17} strokeWidth={1.8}/>Settings</button>
      <div className="lm-sidebar-foot"><div style={{display:'flex',alignItems:'center',gap:10,padding:'0 9px'}}><div className="lm-avatar" style={{background:'#bf8624'}}>JM</div><div><div style={{fontSize:12,fontWeight:600}}>Jordan Miller</div><div style={{fontSize:10,color:'#91b0aa',marginTop:2}}>Guardian account</div></div></div></div>
    </aside>
    <section className="lm-main"><header className="lm-topbar"><button className="lm-menu" onClick={()=>toast('Navigation menu')}><Menu size={21}/></button><div className="lm-crumb"><span>Workspace</span><ChevronRight size={13}/><strong>{tab}</strong></div><div className="lm-top-actions"><button className="lm-icon-button" onClick={()=>toast('No new notifications')}><Bell size={17}/></button><button className="lm-avatar" style={{background:'#bf8624',border:0,cursor:'pointer'}} onClick={()=>toast('Profile menu opened')}>JM</button></div></header>
      <div className="lm-content"><div className="lm-welcome"><div><div className="lm-eyebrow">Tuesday · 14 May 2024</div><h1 className="lm-h1">Good morning, <em>Jordan.</em></h1></div><div className="lm-date"><b>One small check-in at a time.</b>Miso's daily care plan</div></div>
        <div className="lm-grid"><div style={{display:'flex',flexDirection:'column',gap:22}}><article className="lm-card lm-hero"><div className="lm-pet-select"><button className="lm-pet-button" onClick={()=>setShowPetMenu(!showPetMenu)}><span className="lm-pet-photo" style={{background:pet.tone}}>{pet.initials}</span><span><span className="lm-pet-name">{pet.name} <ChevronDown size={15} style={{verticalAlign:'-2px'}}/></span><span className="lm-pet-meta">{pet.species} · <span style={{color:'#268c87'}}>● {pet.status}</span></span></span></button><button className="lm-icon-button" style={{background:'#edf7f3',borderColor:'#c8e2db'}} onClick={()=>toast('Pet profile opened')}><MoreHorizontal size={18}/></button></div>
          {showPetMenu&&<div className="lm-pet-menu">{petData.map((p,i)=><button key={p.name} onClick={()=>{setActivePet(i);setShowPetMenu(false);toast(`${p.name}'s dashboard selected`)}}>{p.name} <span style={{color:'#9aa9a5'}}>· {p.species.split(' · ')[0]}</span></button>)}</div>}<div className="lm-health"><div><div className="lm-health-label">Weekly wellness</div><div className="lm-health-score">82 <small>/ 100</small></div><div style={{fontSize:11,color:'#65827c',marginTop:4}}>Looking steady this week</div></div><div className="lm-ring"><span>82%</span></div></div><div className="lm-progress"><i/></div></article>
          <article className="lm-card"><div className="lm-card-head"><div><div className="lm-eyebrow" style={{marginBottom:5}}>Daily plan</div><div className="lm-card-title">{completed} of {tasks.length} check-ins complete</div></div><button className="lm-card-link" onClick={()=>toast('Showing full health log')}>View log <ChevronRight size={12} style={{verticalAlign:'-2px'}}/></button></div><div className="lm-tasks">{tasks.map(task=><div className={`lm-task ${task.done?'is-done':''}`} key={task.id}><span className="lm-task-time">{task.time}</span><IconTile kind={task.kind}/><span><span className="lm-task-title">{task.title}</span><span className="lm-task-detail">{task.detail}</span></span><button className={`lm-check ${task.done?'checked':''}`} onClick={()=>{toggleTask(task.id);toast(task.done?'Check-in reopened':'Check-in recorded')}} aria-label={`Mark ${task.title} ${task.done?'incomplete':'complete'}`}>{task.done&&<Check size={14}/>}</button></div>)}</div>{showComposer?<div className="lm-composer"><input autoFocus placeholder="e.g. Nail trim at 18:00" onKeyDown={e=>{if(e.key==='Enter'){setShowComposer(false);toast('Care note added')}}}/><button onClick={()=>{setShowComposer(false);toast('Care note added')}}>Add</button><button onClick={()=>setShowComposer(false)} style={{background:'#e7f0ed',color:'#587771',padding:10}}><X size={14}/></button></div>:<div style={{padding:'0 23px 19px'}}><button className="lm-add" onClick={()=>setShowComposer(true)}><Plus size={14} style={{verticalAlign:'-3px',marginRight:5}}/>Add a care note</button></div>}</article></div>
          <div className="lm-side-stack"><article className="lm-card lm-stat-card"><div className="lm-stat-row"><div><div className="lm-eyebrow" style={{marginBottom:8}}>Hydration · today</div><div className="lm-stat-main">620 <small>/ 800 ml</small></div><div className="lm-stat-note">78% of daily target</div></div><span className="lm-stat-icon"><Droplets size={18}/></span></div><div className="lm-mini-chart">{[34,48,28,62,48,72].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div style={{fontSize:10,color:'#8ea09b',display:'flex',justifyContent:'space-between',marginTop:7}}><span>6 am</span><span>now</span></div></article>
            <article className="lm-card lm-next"><div className="lm-card-head" style={{padding:0}}><div><div className="lm-eyebrow" style={{marginBottom:5}}>Next appointment</div><div className="lm-card-title">Annual wellness exam</div></div><Stethoscope size={20} color="#bf8624"/></div><div className="lm-next-box"><CalendarDays size={17} color="#bf8624"/><div><strong>Thursday, 23 May</strong><span>10:30 · Cedar Grove Vet</span></div></div><button className="lm-add" onClick={()=>toast('Appointment details opened')}>View appointment <ChevronRight size={13} style={{verticalAlign:'-2px'}}/></button></article>
            <article className="lm-card" style={{padding:'20px 22px',background:'#e5f2e7',borderColor:'#c9e3d0'}}><div style={{display:'flex',gap:11,alignItems:'flex-start'}}><ShieldCheck size={20} color="#338681"/><div><div style={{fontSize:13,fontWeight:700,color:'#315d56'}}>Everything looks on track</div><div style={{fontSize:11,color:'#66867d',lineHeight:1.5,marginTop:5}}>Miso's routine is 3 days stronger than last week.</div></div></div></article>
          </div></div></div></section>{notice&&<div className="lm-toast"><Sparkles size={13} style={{verticalAlign:'-2px',marginRight:7,color:'#e0aa3f'}}/>{notice}</div>}
  </main>;
}