'use strict';

const fs = require('fs');
const path = require('path');
const { loadBaseline } = require('./baseline');
const { gateChanges } = require('./gate-changes');
const { findDuplicateRequirementIds, gateIds } = require('./gate-ids');
const { collectFeatureDocs } = require('./gate-report');
const { buildBddIndex, gateTrace } = require('./gate-trace');

function runHygieneReport(root, options = {}) {
  const baseline = loadBaseline(root);
  const diffFiles = collectFeatureDocs(root).concat([...baseline.changes]);
  const ctx = {
    root,
    base: 'HEAD',
    head: 'HEAD',
    diffFiles,
    baseline,
    clock: options.clock,
    scanAll: true,
  };

  const sections = [];
  const changeFindings = gateChanges(ctx);
  const stale = changeFindings.filter((f) => f.ruleId === 'R-B5');
  if (stale.length) {
    sections.push('## Stale proposed change docs (R-B5)\n');
    for (const f of stale) {
      sections.push(`- ${f.message.split(' Fix:')[0]}`);
    }
  }

  const dups = findDuplicateRequirementIds(root, collectFeatureDocs(root));
  if (dups.length) {
    sections.push('\n## Duplicate requirement IDs on main (R-D3-report)\n');
    for (const { id, files } of dups) {
      sections.push(`- \`${id}\`: ${files.join(', ')}`);
    }
  }

  const noneIssues = findNoneCoverageClosedIssues(root, options);
  if (noneIssues.length) {
    sections.push('\n## none — #issue references (R-T4)\n');
    for (const line of noneIssues) {
      sections.push(`- ${line}`);
    }
  }

  return sections.join('\n');
}

function findNoneCoverageClosedIssues(root, options) {
  const lines = [];
  const closed = options.closedIssues || new Set();
  for (const rel of collectFeatureDocs(root)) {
    const full = path.join(root, rel);
    let body;
    try {
      ({ body } = require('./yaml').parseFrontmatter(full, root));
    } catch {
      continue;
    }
    const { parseAcceptanceCriteria } = require('./parse-md');
    for (const row of parseAcceptanceCriteria(body)) {
      const m = String(row.coverage || '').match(/none\s*—\s*#(\d+)/i);
      if (m && closed.has(Number(m[1]))) {
        lines.push(`${rel}: none — #${m[1]} (issue closed)`);
      }
    }
  }
  return lines;
}

function formatTrackingIssueBody(reportMd) {
  return `<!-- docs-hygiene -->

# Weekly documentation hygiene

${reportMd}

_Auto-generated by quality-kpis workflow._
`;
}

module.exports = { runHygieneReport, formatTrackingIssueBody, findNoneCoverageClosedIssues };
