#!/usr/bin/env node
/**
 * Generate test/generated/coverage_helper_imports.dart so every eligible domain
 * file is loaded during `flutter test --coverage` (J.1-1).
 *
 * Usage: node scripts/generate_coverage_helper.js [--check]
 */
const fs = require('fs');
const path = require('path');

const {
  listEligibleDomainSources,
  libPathToPackageUri,
} = require('./domain_coverage_lib');

const flutterRoot = path.resolve(__dirname, '..');
const outPath = path.join(flutterRoot, 'test', 'generated', 'coverage_helper_imports.dart');

function buildDartSource(files) {
  const lines = [
    '// GENERATED by flutter_app/scripts/generate_coverage_helper.js — do not edit.',
    '// ignore_for_file: unused_import',
    '',
  ];
  for (const file of files) {
    lines.push(`import '${libPathToPackageUri(file)}';`);
  }
  lines.push('', `const int coverageHelperDomainFileCount = ${files.length};`, '');
  return lines.join('\n');
}

function main() {
  const checkOnly = process.argv.includes('--check');
  const files = listEligibleDomainSources(flutterRoot);
  const next = buildDartSource(files);

  if (checkOnly) {
    if (!fs.existsSync(outPath)) {
      console.error(`::error::Missing ${outPath} — run generate_coverage_helper.js`);
      process.exit(1);
    }
    const current = fs.readFileSync(outPath, 'utf8');
    if (current !== next) {
      console.error(
        `::error::${outPath} is stale — run node scripts/generate_coverage_helper.js`,
      );
      process.exit(1);
    }
    console.log(`coverage_helper_imports.dart OK (${files.length} domain files)`);
    return;
  }

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, next);
  console.log(`Wrote ${outPath} (${files.length} imports)`);
}

main();
