// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/guardian-operations/GuardianOperationsEmptyState.tsx": () => import("../components/mockups/guardian-operations/GuardianOperationsEmptyState.tsx"),
  "./components/mockups/guardian-operations/GuardianOperationsExpandedPet.tsx": () => import("../components/mockups/guardian-operations/GuardianOperationsExpandedPet.tsx"),
  "./components/mockups/guardian-operations/GuardianOperationsMobileState.tsx": () => import("../components/mockups/guardian-operations/GuardianOperationsMobileState.tsx")
};
